"use client";

export default function RemoveAssignmentButton({
  assignmentId,
  companyName,
  ticketName,
  action,
}: {
  assignmentId: string;
  companyName: string;
  ticketName: string;
  action: (data: FormData) => void;
}) {
  return (
    <form
      action={action}
      onSubmit={(event) => {
        if (!window.confirm(`Remove “${ticketName}” from ${companyName}? This stops future tickets from being generated by this assignment. Existing collection records remain in the audit trail.`)) {
          event.preventDefault();
        }
      }}
    >
      <input type="hidden" name="assignmentId" value={assignmentId} />
      <button className="assignment-remove-action" type="submit">Remove assignment</button>
    </form>
  );
}
