"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Application = { id: string; first_name: string; last_name: string; email: string; role_interest?: string | null; location_interest?: string | null; source_type: string; application_status: string; scheduling_policy: string; submitted_at: string; roster_id?: string | null };

export default function FoyerApplicationInbox({ slug, onAdvanced }: { slug: string; onAdvanced: () => void }) {
  const [applications, setApplications] = useState<Application[]>([]); const [error, setError] = useState(""); const [busyId, setBusyId] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/company/${slug}/hiring/applications`, { cache: "no-store", credentials: "include" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to load Foyer applications."); setApplications(body.applications || []); }, [slug]);
  useEffect(() => { if (slug) void load().catch((reason) => setError(reason.message)); }, [load, slug]);
  async function advance(applicationId: string) { setBusyId(applicationId); setError(""); try { const response = await fetch(`/api/company/${slug}/hiring/applications`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "advance", applicationId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to advance this candidate."); await load(); onAdvanced(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to advance this candidate."); } finally { setBusyId(""); } }
  const pending = applications.filter((item) => !item.roster_id && !["declined", "withdrawn"].includes(item.application_status));
  return <article className="value-card" style={{ padding: 18 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}><div><p className="value-card__eyebrow">Foyer application inbox</p><h3 className="value-card__title">Introductions waiting for review</h3><p className="value-card__body">Candidates remain outside the company roster until you deliberately advance them.</p></div><div className="cta-row"><Link className="button" href={`/company/${slug}/people/invitations`}>Invitation links</Link><Link className="button" href={`/company/${slug}/people/interviews`}>Interview agenda</Link></div></div>{error ? <p style={{ color: "#b91c1c", fontWeight: 700 }}>{error}</p> : null}<div style={{ display: "grid", gap: 10, marginTop: 14 }}>{pending.length ? pending.map((item) => <div key={item.id} style={{ border: "1px solid #dbe4ef", borderRadius: 14, padding: 14, display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center", flexWrap: "wrap" }}><div><strong>{item.first_name} {item.last_name}</strong><p style={{ margin: "4px 0" }}>{item.role_interest || "Open role"}{item.location_interest ? ` · ${item.location_interest}` : ""} · {item.email}</p><small>{item.source_type.replaceAll("_", " ")} · {item.application_status.replaceAll("_", " ")} · interview {item.scheduling_policy}</small></div><button className="button button-primary" disabled={busyId === item.id} onClick={() => void advance(item.id)}>{busyId === item.id ? "Advancing…" : "Advance to hiring"}</button></div>) : <p>No new Foyer applications are waiting.</p>}</div></article>;
}
