"use client";

import { useMemo, useState } from "react";
import type { CalendarOverlay, OperatingDayPoint, OperatingWeekPoint } from "./operatingIntelligence";

type Grain = "day" | "week" | "month";
type Point = { key: string; label: string; start: string; end: string; stops: number; packages: number; routes: number; signal: string | null };
const fmt = (value: number, digits = 0) => new Intl.NumberFormat(undefined, { maximumFractionDigits: digits }).format(value);
const dateLabel = (value: string, grain: Grain) => new Intl.DateTimeFormat(undefined, { month: "short", day: grain === "month" ? undefined : "numeric", year: grain === "month" ? "numeric" : undefined, timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`));

function pointsFor(grain: Grain, days: OperatingDayPoint[], weeks: OperatingWeekPoint[]): Point[] {
  if (grain === "day") return days.map((day) => ({ key: day.serviceDate, label: dateLabel(day.serviceDate, grain), start: day.serviceDate, end: day.serviceDate, stops: day.totalStops, packages: day.totalPackages, routes: day.routeCount, signal: day.signal }));
  if (grain === "week") return weeks.map((week) => ({ key: week.weekKey, label: dateLabel(week.weekStart, grain), start: week.weekStart, end: week.weekEnd, stops: week.totalStops, packages: week.totalPackages, routes: week.averageRoutes, signal: week.supplementalDays ? "SUPPLEMENTAL_OPERATION" : null }));
  const map = new Map<string, Point & { operatingDays: number }>();
  for (const day of days) { const key = day.serviceDate.slice(0, 7); const current = map.get(key) ?? { key, label: dateLabel(`${key}-01`, grain), start: `${key}-01`, end: day.serviceDate, stops: 0, packages: 0, routes: 0, signal: null, operatingDays: 0 }; current.stops += day.totalStops; current.packages += day.totalPackages; current.routes += day.routeCount; current.operatingDays += 1; current.end = day.serviceDate; current.signal ||= day.signal; map.set(key, current); }
  return [...map.values()].map(({ operatingDays, ...point }) => ({ ...point, routes: operatingDays ? point.routes / operatingDays : 0 }));
}

export default function CompositeOperatingChart({ days, weeks, overlays, compact = false }: { days: OperatingDayPoint[]; weeks: OperatingWeekPoint[]; overlays: CalendarOverlay[]; compact?: boolean }) {
  const [grain, setGrain] = useState<Grain>(compact ? "week" : "day");
  const [layers, setLayers] = useState({ stops: true, packages: true, routes: true });
  const [active, setActive] = useState<number | null>(null);
  const points = useMemo(() => pointsFor(grain, days, weeks), [grain, days, weeks]);
  const width = 1160, height = compact ? 360 : 440, margin = { top: 34, right: 66, bottom: 54, left: 66 };
  const plotWidth = width - margin.left - margin.right, plotHeight = height - margin.top - margin.bottom;
  const stopMax = Math.max(...points.map((point) => point.stops), 1), packageMax = Math.max(...points.map((point) => point.packages), 1), routeMax = Math.max(...points.map((point) => point.routes), 1);
  const step = plotWidth / Math.max(points.length, 1), x = (index: number) => margin.left + step * index + step / 2;
  const yStops = (value: number) => margin.top + plotHeight - value / stopMax * plotHeight;
  const yPackages = (value: number) => margin.top + plotHeight - value / packageMax * plotHeight;
  const area = `${margin.left},${margin.top + plotHeight} ${points.map((point, index) => `${x(index)},${yPackages(point.packages)}`).join(" ")} ${margin.left + plotWidth},${margin.top + plotHeight}`;
  const labelEvery = Math.max(1, Math.ceil(points.length / 12));
  const activePoint = active == null ? null : points[active];
  return <article className="app-card" style={{ padding: 0, overflow: "hidden" }}>
    <div style={{ padding: 18, display: "flex", justifyContent: "space-between", gap: 18, flexWrap: "wrap" }}><div><p className="value-card__eyebrow">Demand and deployed capacity</p><h2 className="app-card__title" style={{ fontSize: compact ? 21 : 27 }}>Operating relationship</h2><p className="app-card__body" style={{ marginTop: 5 }}>Stops form the operating load, packages show handling volume, and route bubbles show capacity placed against demand.</p></div><div style={{ display: "flex", gap: 12, alignItems: "end", flexWrap: "wrap" }}><div style={{ display: "flex", gap: 4 }}>{(["day","week","month"] as Grain[]).filter((item) => !compact || item !== "day").map((item) => <button key={item} className={`app-button ${grain === item ? "app-button--primary" : "app-button--secondary"}`} style={{ minHeight: 32, padding: "5px 9px" }} onClick={() => setGrain(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>{(["stops","packages","routes"] as const).map((layer) => <label key={layer} style={{ fontSize: 12, fontWeight: 800, textTransform: "capitalize" }}><input type="checkbox" checked={layers[layer]} onChange={() => setLayers((current) => ({ ...current, [layer]: !current[layer] }))} /> {layer}</label>)}</div></div>
    <div style={{ position: "relative", padding: "0 10px 14px" }}>{activePoint ? <div style={{ position: "absolute", zIndex: 3, top: 10, right: 22, padding: "10px 12px", border: "1px solid #cbd5e1", borderRadius: 10, background: "rgba(255,255,255,.96)", boxShadow: "0 8px 24px rgba(15,23,42,.12)", fontSize: 12 }}><strong>{activePoint.label}</strong><div>{fmt(activePoint.stops)} stops · {fmt(activePoint.packages)} packages · {fmt(activePoint.routes, 1)} routes</div><div>{fmt(activePoint.stops / Math.max(activePoint.routes, 1), 1)} stops/route</div>{activePoint.signal ? <div style={{ marginTop: 3, color: "#b45309", fontWeight: 800 }}>{activePoint.signal === "SUPPLEMENTAL_OPERATION" ? "Supplemental operation" : "Possible capacity intervention"}</div> : null}</div> : null}<svg viewBox={`0 0 ${width} ${height}`} style={{ width: "100%", display: "block" }} onMouseLeave={() => setActive(null)} role="img" aria-label="Stops, packages, and routes over time">
      {overlays.map((overlay) => { const indexes = points.map((point, index) => point.end >= overlay.startDate && point.start <= overlay.endDate ? index : -1).filter((index) => index >= 0); if (!indexes.length) return null; const left = x(indexes[0]) - step/2, right = x(indexes.at(-1)!) + step/2; return <g key={overlay.key}><rect x={left} y={margin.top} width={right-left} height={plotHeight} fill={overlay.kind === "PEAK_RAMP" ? "#f59e0b" : "#7c3aed"} opacity={overlay.kind === "PEAK_RAMP" ? .1 : .07}/><text x={(left+right)/2} y={margin.top+13} textAnchor="middle" fontSize="10" fontWeight="800" fill={overlay.kind === "PEAK_RAMP" ? "#b45309" : "#6d28d9"}>{overlay.kind === "PEAK_RAMP" ? "Demand ramp" : "Peak Season"}</text></g>; })}
      {[0,.25,.5,.75,1].map((fraction) => <g key={fraction}><line x1={margin.left} x2={margin.left+plotWidth} y1={margin.top+plotHeight*(1-fraction)} y2={margin.top+plotHeight*(1-fraction)} stroke="#e2e8f0"/><text x={margin.left-10} y={margin.top+plotHeight*(1-fraction)+4} textAnchor="end" fontSize="10" fill="#64748b">{fmt(stopMax*fraction)}</text></g>)}
      {layers.packages && points.length > 1 ? <polygon points={area} fill="#60a5fa" opacity=".2" stroke="#2563eb" strokeWidth="2"/> : null}
      {points.map((point, index) => <g key={point.key}><rect x={x(index)-step/2} y={margin.top} width={step} height={plotHeight} fill="transparent" onMouseEnter={() => setActive(index)}/>{layers.stops ? <rect x={x(index)-Math.max(1,step*.24)} y={yStops(point.stops)} width={Math.max(2,step*.48)} height={margin.top+plotHeight-yStops(point.stops)} rx="2" fill="#334155" opacity=".78" pointerEvents="none"/> : null}{layers.routes ? <><circle cx={x(index)} cy={margin.top+plotHeight-8} r={3+point.routes/routeMax*9} fill="#f59e0b" stroke="#92400e" strokeWidth="1" opacity=".88" pointerEvents="none"/>{grain !== "day" ? <text x={x(index)} y={margin.top+plotHeight-5} textAnchor="middle" fontSize={point.routes >= 100 ? "7" : "8"} fontWeight="900" fill="#451a03" pointerEvents="none">{fmt(point.routes, point.routes < 10 ? 1 : 0)}</text> : null}</> : null}{point.signal ? <path d={`M ${x(index)-5} ${margin.top+4} L ${x(index)+5} ${margin.top+4} L ${x(index)} ${margin.top+14} Z`} fill={point.signal === "SUPPLEMENTAL_OPERATION" ? "#d97706" : "#dc2626"} pointerEvents="none"/> : null}{(index % labelEvery === 0 || index === points.length-1) ? <text x={x(index)} y={height-18} textAnchor="middle" fontSize="10" fill="#64748b">{point.label}</text> : null}</g>)}
      <text x={margin.left} y={18} fontSize="10" fill="#475569">Stops</text><text x={width-margin.right} y={18} textAnchor="end" fontSize="10" fill="#2563eb">Packages scaled independently</text>
    </svg></div>
  </article>;
}
