#!/usr/bin/env python3
"""Generate ZIP Code Business Patterns enrichment SQL."""

import argparse
import csv
import io
import zipfile
from pathlib import Path


def sql_text(value):
    return "null" if not value else "'" + value.replace("'", "''") + "'"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    with zipfile.ZipFile(args.source) as archive:
        name = next(item for item in archive.namelist() if item.lower().endswith(".txt"))
        rows = list(csv.DictReader(io.TextIOWrapper(archive.open(name), encoding="utf-8-sig", newline="")))

    lines = ["-- Generated by scripts/generate-zip-commercial-data.py; do not edit by hand."]
    for start in range(0, len(rows), 1000):
        values = []
        for row in rows[start:start + 1000]:
            values.append(f"('{row['zip']}', {row['est'] or 'null'}, {row['emp'] or 'null'}, {row['ap'] or 'null'}, {sql_text(row['emp_nf'])}, {sql_text(row['ap_nf'])})")
        lines.extend([
            "update ref.zip_code as target set",
            "  business_establishments = source.establishments, business_employment = source.employment,",
            "  business_annual_payroll_thousands = source.annual_payroll, business_employment_noise_flag = source.employment_flag,",
            "  business_payroll_noise_flag = source.payroll_flag, commercial_source = 'US_CENSUS_ZBP', commercial_vintage = 2023",
            "from (values", ",\n".join(values),
            ") as source(zip_code, establishments, employment, annual_payroll, employment_flag, payroll_flag)",
            "where target.zip_code = source.zip_code;",
        ])
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {len(rows):,} ZIP business rows")


if __name__ == "__main__":
    main()
