#!/usr/bin/env python3
"""Generate USDA RUCA ZIP enrichment SQL."""

import argparse
import csv
from pathlib import Path


def category(primary):
    if primary <= 3:
        return "METROPOLITAN"
    if primary <= 6:
        return "MICROPOLITAN"
    if primary <= 9:
        return "SMALL_TOWN"
    return "RURAL"


def factor(primary):
    return {"METROPOLITAN": "0.00", "MICROPOLITAN": "0.33", "SMALL_TOWN": "0.67", "RURAL": "1.00"}[category(primary)]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    with args.source.open(encoding="utf-8-sig", newline="") as source:
        rows = list(csv.DictReader(source))

    lines = ["-- Generated by scripts/generate-zip-ruca-data.py; do not edit by hand."]
    for start in range(0, len(rows), 1000):
        values = []
        for row in rows[start:start + 1000]:
            primary = int(float(row["PrimaryRUCA"]))
            secondary = row["SecondaryRUCA"]
            values.append(
                f"('{row['ZIPCode'].zfill(5)}', {primary}, {secondary}, '{category(primary)}', {factor(primary)})"
            )
        lines.extend([
            "update ref.zip_code as target set",
            "  ruca_primary_code = source.primary_code, ruca_secondary_code = source.secondary_code,",
            "  ruca_category = source.category, rurality_factor = source.rurality_factor,",
            "  rurality_source = 'USDA_ERS_RUCA', rurality_vintage = 2020",
            "from (values", ",\n".join(values),
            ") as source(zip_code, primary_code, secondary_code, category, rurality_factor)",
            "where target.zip_code = source.zip_code;",
        ])

    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {len(rows):,} USDA RUCA ZIP rows")


if __name__ == "__main__":
    main()
