#!/usr/bin/env python3
"""Generate the deterministic ZIP reference data migration from approved source archives."""

from __future__ import annotations

import argparse
import csv
import io
import struct
import zipfile
from collections import OrderedDict
from datetime import date
from pathlib import Path


CLASSIFICATION = {"": "STANDARD", "S": "STANDARD", "P": "PO_BOX", "U": "UNIQUE", "M": "MILITARY"}
HUD_COVERAGE_DATE = date(2023, 12, 1)


def clean(value: str) -> str:
    return " ".join(value.strip().split())


def sql_text(value: str | None) -> str:
    if value is None:
        return "null"
    return "'" + value.replace("'", "''") + "'"


def read_vendor(archive: Path):
    with zipfile.ZipFile(archive) as bundle:
        csv_name = next(name for name in bundle.namelist() if name.lower().endswith(".csv"))
        with bundle.open(csv_name) as raw:
            reader = csv.DictReader(io.TextIOWrapper(raw, encoding="utf-8-sig", newline=""))
            rows = list(reader)

    canonical: OrderedDict[str, dict] = OrderedDict()
    aliases: set[tuple[str, str, str]] = set()
    for row in rows:
        zipcode = row["ZipCode"].strip().zfill(5)
        city = clean(row["City"])
        state = row["State"].strip().upper()
        aliases.add((zipcode, city, state))
        canonical.setdefault(
            zipcode,
            {
                "zip_code": zipcode,
                "preferred_city": city,
                "state_code": state,
                "classification": CLASSIFICATION[row["Classification"].strip().upper()],
                "population": int(row["Population"]) if row["Population"].strip() else None,
                "latitude": float(row["Latitude"]),
                "longitude": float(row["Longitude"]),
                "coordinate_source": "ZIP_CODES_COM",
                "coordinate_method": "VENDOR_CENTROID",
                "hud_source_present": False,
                "source_coverage_date": None,
            },
        )
    return canonical, aliases


def read_dbf(raw: bytes):
    record_count = struct.unpack_from("<I", raw, 4)[0]
    header_length, record_length = struct.unpack_from("<HH", raw, 8)
    fields = []
    offset = 32
    while raw[offset] != 0x0D:
        descriptor = raw[offset : offset + 32]
        name = descriptor[:11].split(b"\0", 1)[0].decode("ascii")
        fields.append((name, chr(descriptor[11]), descriptor[16], descriptor[17]))
        offset += 32
    for index in range(record_count):
        record = raw[header_length + index * record_length : header_length + (index + 1) * record_length]
        if not record or record[0:1] == b"*":
            continue
        cursor = 1
        result = {}
        for name, field_type, length, decimals in fields:
            value = record[cursor : cursor + length].decode("latin-1").strip()
            cursor += length
            if field_type in ("N", "F") and value:
                result[name] = float(value) if decimals else int(value)
            else:
                result[name] = value
        yield result


def read_hud(archive: Path):
    with zipfile.ZipFile(archive) as bundle:
        dbf_name = next(name for name in bundle.namelist() if name.lower().endswith(".dbf"))
        return list(read_dbf(bundle.read(dbf_name)))


def merge(canonical, aliases, hud_rows):
    for row in hud_rows:
        zipcode = str(row["STD_ZIP5"]).zfill(5)
        if zipcode not in canonical:
            raise ValueError(f"HUD ZIP {zipcode} is absent from the vendor source")
        target = canonical[zipcode]
        target.update(
            preferred_city=clean(str(row["USPS_ZIP_P"])),
            state_code=clean(str(row["USPS_ZIP_1"])).upper(),
            latitude=float(row["LATITUDE"]),
            longitude=float(row["LONGITUDE"]),
            coordinate_source="HUD",
            coordinate_method="POPULATION_WEIGHTED_RESIDENTIAL",
            hud_source_present=True,
            source_coverage_date=HUD_COVERAGE_DATE,
        )
        aliases.add((zipcode, target["preferred_city"], target["state_code"]))


def write_migration(output: Path, canonical, aliases):
    lines = ["-- Generated by scripts/generate-zip-reference-data.py; do not edit by hand."]
    values = []
    for row in canonical.values():
        values.append(
            "(" + ", ".join(
                [
                    sql_text(row["zip_code"]), sql_text(row["preferred_city"]), sql_text(row["state_code"]),
                    sql_text(row["classification"]), str(row["population"]) if row["population"] is not None else "null",
                    repr(row["latitude"]), repr(row["longitude"]), sql_text(row["coordinate_source"]),
                    sql_text(row["coordinate_method"]), "true", "true" if row["hud_source_present"] else "false",
                    sql_text(row["source_coverage_date"].isoformat()) if row["source_coverage_date"] else "null",
                ]
            ) + ")"
        )
    for start in range(0, len(values), 1000):
        lines.append("insert into ref.zip_code (zip_code, preferred_city, state_code, classification, population, latitude, longitude, coordinate_source, coordinate_method, vendor_source_present, hud_source_present, source_coverage_date) values")
        lines.append(",\n".join(values[start : start + 1000]) + ";")
    alias_values = []
    for zipcode, city, state in sorted(aliases):
        preferred = canonical[zipcode]["preferred_city"] == city and canonical[zipcode]["state_code"] == state
        source = "HUD" if preferred and canonical[zipcode]["hud_source_present"] else "ZIP_CODES_COM"
        alias_values.append(f"({sql_text(zipcode)}, {sql_text(city)}, {sql_text(state)}, {'true' if preferred else 'false'}, {sql_text(source)})")
    for start in range(0, len(alias_values), 1000):
        lines.append("insert into ref.zip_city_alias (zip_code, city, state_code, is_preferred, source) values")
        lines.append(",\n".join(alias_values[start : start + 1000]) + ";")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--vendor", type=Path, required=True)
    parser.add_argument("--hud", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    canonical, aliases = read_vendor(args.vendor)
    merge(canonical, aliases, read_hud(args.hud))
    write_migration(args.output, canonical, aliases)
    print(f"generated {len(canonical):,} ZIPs and {len(aliases):,} aliases at {args.output}")


if __name__ == "__main__":
    main()
