#!/usr/bin/env python3
"""Generate the ACS population and Gazetteer land-area ZIP enrichment migration."""

import argparse
import csv
import io
import zipfile
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--population", type=Path, required=True)
    parser.add_argument("--gazetteer", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    population = {}
    with zipfile.ZipFile(args.population) as archive:
        name = next(item for item in archive.namelist() if item.lower().endswith(".csv"))
        reader = csv.DictReader(io.TextIOWrapper(archive.open(name), encoding="utf-8-sig", newline=""))
        for row in reader:
            if row.get("ORDER") == "1" and row.get("GEOID", "").startswith("860Z200US"):
                population[row["GEOID"][-5:]] = int(row["ESTIMATE"])

    areas = {}
    with zipfile.ZipFile(args.gazetteer) as archive:
        name = next(item for item in archive.namelist() if item.lower().endswith(".txt"))
        reader = csv.DictReader(io.TextIOWrapper(archive.open(name), encoding="utf-8-sig"), delimiter="\t")
        for row in reader:
            areas[row["GEOID"]] = row["ALAND_SQMI"].strip()

    rows = [(zipcode, value, areas[zipcode]) for zipcode, value in population.items() if zipcode in areas]
    lines = ["-- Generated by scripts/generate-zip-demographic-data.py; do not edit by hand."]
    for start in range(0, len(rows), 1000):
        values = ",\n".join(f"('{zipcode}', {pop}, {area})" for zipcode, pop, area in rows[start:start + 1000])
        lines.extend([
            "update ref.zip_code as target set",
            "  zcta_population = source.population,",
            "  zcta_land_area_sqmi = source.land_area_sqmi,",
            "  demographic_source = 'US_CENSUS_ACS_GAZETTEER',",
            "  demographic_vintage = 2024",
            "from (values",
            values,
            ") as source(zip_code, population, land_area_sqmi)",
            "where target.zip_code = source.zip_code;",
        ])
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {len(rows):,} ZCTA demographic rows")


if __name__ == "__main__":
    main()
