begin;

-- The July 10 row was generated by Stripe test mode. It has no durable invoice,
-- charge, receipt, provider-event ledger entry, readiness use, or accounting
-- value. Remove only the exact inspected row; preserve the August 1 live chain.
do $$
declare
  v_company_id constant uuid := '0385bc8f-eb13-490b-92c8-f34bad2507df';
  v_test_payment_id constant uuid := '80d1ebca-187c-4926-b05e-66bc0dd5c1b1';
  v_test_checkout_id constant text := 'cs_test_a1A3MiwUbGPU5E9Cp5AEBGDSoWh6k1huORGcAJLNFpgls5vYCIGp7W90Xb';
  v_test_intent_id constant text := 'pi_3Trg1eQzmoWEViMv0jK6Ri0Q';
  v_test_event_id constant text := 'evt_1Trg1fQzmoWEViMv2TSjR1nm';
  v_match_count integer;
begin
  if not exists (
    select 1
    from core.companies company
    where company.id = v_company_id
      and company.company_slug = 'beacon-point-ventures'
  ) then
    raise exception 'Beacon Point company identity does not match';
  end if;

  select count(*)
  into v_match_count
  from billing.payment payment
  where payment.id = v_test_payment_id
    and payment.company_id = v_company_id
    and payment.provider = 'stripe'
    and payment.payment_purpose = 'implementation'
    and payment.provider_checkout_session_id = v_test_checkout_id
    and payment.provider_payment_intent_id = v_test_intent_id
    and payment.provider_event_id = v_test_event_id
    and payment.provider_livemode is false
    and payment.amount = 398.00
    and payment.currency = 'usd'
    and payment.payment_status = 'paid'
    and payment.paid_at = '2026-07-10T15:07:39+00:00'::timestamptz
    and payment.invoice_id is null
    and payment.provider_invoice_id is null
    and payment.provider_charge_id is null
    and payment.receipt_url is null;

  if v_match_count <> 1 then
    raise exception
      'Expected exactly one fully matched Beacon Point sandbox payment row, found %',
      v_match_count;
  end if;

  if exists (
    select 1
    from billing.provider_event event
    where event.provider_event_id = v_test_event_id
      or event.object_id in (v_test_checkout_id, v_test_intent_id)
  ) then
    raise exception 'Sandbox payment has provider-event ledger references';
  end if;

  if exists (
    select 1
    from commercial.company_activation_readiness readiness
    where readiness.company_id = v_company_id
      and (
        readiness.metadata::text like '%' || v_test_payment_id::text || '%'
        or readiness.metadata::text like '%' || v_test_checkout_id || '%'
        or readiness.metadata::text like '%' || v_test_intent_id || '%'
        or readiness.metadata::text like '%' || v_test_event_id || '%'
      )
  ) then
    raise exception 'Sandbox payment has activation-readiness references';
  end if;

  if exists (
    select 1
    from billing.subscription subscription
    where subscription.company_id = v_company_id
      and subscription.provider_metadata::text like '%' || v_test_payment_id::text || '%'
  ) then
    raise exception 'Sandbox payment has subscription metadata references';
  end if;

  delete from billing.payment
  where id = v_test_payment_id
    and company_id = v_company_id
    and provider_checkout_session_id = v_test_checkout_id
    and provider_livemode is false;

  if exists (
    select 1
    from billing.payment payment
    where payment.company_id = v_company_id
      and (
        payment.provider_livemode is false
        or payment.provider_checkout_session_id like 'cs_test_%'
      )
  ) then
    raise exception 'Beacon Point still contains sandbox payment evidence';
  end if;

  if not exists (
    select 1
    from billing.payment payment
    where payment.company_id = v_company_id
      and payment.provider_checkout_session_id = 'cs_live_a1eY9XiZBY4u7mYN77gweVmguQO97BSaTxGxQGH7KsprMe1KY8TD5KvO2j'
      and payment.provider_livemode is true
      and payment.payment_status = 'paid'
      and payment.provider_invoice_id = 'in_1TzdqDJeXupVRq0Vbh1GYYjk'
  ) then
    raise exception 'Verified Beacon Point live payment was not preserved';
  end if;
end;
$$;

commit;
