-- Controlled first-pass ITG roster import from the donor application.
--
-- The platform roster remains authoritative. Telecom identifiers use the same
-- extensible identifier contract as the existing commercial product. This load
-- is idempotent by donor person ID and preserves donor assignment context in the
-- roster event ledger.
--
-- Imported scope:
--   * 37 active ITG assignments in PC 410 and PC 427;
--   * 1 active ITG director person required by the reporting hierarchy;
--   * no contractor or Locate records.

create temporary table itf_itg_roster_source (
  source_person_id uuid primary key,
  source_assignment_id uuid,
  full_name text not null,
  email text,
  phone text,
  tech_id text,
  fuse_emp_id text,
  nt_login text,
  csg text,
  location_code text,
  position_title text,
  role_type text,
  is_field boolean not null,
  is_leadership boolean not null,
  start_date date,
  end_date date,
  office_name text,
  reports_to_source_person_id uuid,
  reports_to_name text,
  link_platform_owner boolean not null,
  target_roster_id uuid
) on commit drop;

insert into itf_itg_roster_source (
  source_person_id,
  source_assignment_id,
  full_name,
  email,
  phone,
  tech_id,
  fuse_emp_id,
  nt_login,
  csg,
  location_code,
  position_title,
  role_type,
  is_field,
  is_leadership,
  start_date,
  end_date,
  office_name,
  reports_to_source_person_id,
  reports_to_name,
  link_platform_owner
)
select
  source_person_id,
  source_assignment_id,
  full_name,
  email,
  phone,
  tech_id,
  fuse_emp_id,
  nt_login,
  csg,
  location_code,
  position_title,
  role_type,
  is_field,
  is_leadership,
  start_date,
  end_date,
  office_name,
  reports_to_source_person_id,
  reports_to_name,
  link_platform_owner
from jsonb_to_recordset(
  convert_from(decode('W3siY3NnIjogbnVsbCwgImVtYWlsIjogInRlZC5jYXJsc29uQGl0Z2NvbW0uY29tIiwgInBob25lIjogIjMxMjY1OTY0NDAiLCAidGVjaF9pZCI6ICJEaXJlY3RvciIsICJlbmRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImlzX2ZpZWxkIjogZmFsc2UsICJudF9sb2dpbiI6IG51bGwsICJmdWxsX25hbWUiOiAiVGVkIENhcmxzb24iLCAicm9sZV90eXBlIjogIkRJUkVDVE9SIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6IG51bGwsICJvZmZpY2VfbmFtZSI6IG51bGwsICJpc19sZWFkZXJzaGlwIjogdHJ1ZSwgImxvY2F0aW9uX2NvZGUiOiBudWxsLCAicG9zaXRpb25fdGl0bGUiOiAiRGlyZWN0b3IiLCAicmVwb3J0c190b19uYW1lIjogbnVsbCwgInNvdXJjZV9wZXJzb25faWQiOiAiNWNhYWVjMmUtYjA4My00NzE0LWIxN2UtZjg5NzAxZGUzMzk5IiwgImxpbmtfcGxhdGZvcm1fb3duZXIiOiB0cnVlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiNDBmMDY5OTMtMjBiZC00ZDY5LWI0N2QtMzRjMzY0MGYyNmRiIiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6IG51bGx9LCB7ImNzZyI6ICJCRVBQMjQ4MyIsICJlbWFpbCI6ICJicmFkZXBwaW5nZXJAZ21haWwuY29tIiwgInBob25lIjogIjYyOTI1MTg2MjgiLCAidGVjaF9pZCI6ICI0NzQzIiwgImVuZF9kYXRlIjogbnVsbCwgImlzX2ZpZWxkIjogdHJ1ZSwgIm50X2xvZ2luIjogIkJwLWJlcHBpbjI5OSIsICJmdWxsX25hbWUiOiAiQnJhZGxleSBFcHBpbmdlciIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiMTI4MDExIiwgIm9mZmljZV9uYW1lIjogIkhhcnJpc2J1cmciLCAiaXNfbGVhZGVyc2hpcCI6IGZhbHNlLCAibG9jYXRpb25fY29kZSI6ICI0MTAiLCAicG9zaXRpb25fdGl0bGUiOiAiVGVjaG5pY2lhbiIsICJyZXBvcnRzX3RvX25hbWUiOiAiSGFycmlzYnVyZyBbUlJdIiwgInNvdXJjZV9wZXJzb25faWQiOiAiNGNiOTgxZmUtYTE1ZC00Mjk3LWI0ZDgtMDkzNmEyNDA4NmYzIiwgImxpbmtfcGxhdGZvcm1fb3duZXIiOiBmYWxzZSwgInNvdXJjZV9hc3NpZ25tZW50X2lkIjogImIzZDFhNmJkLTU0ZTgtNDAyMS04ZTNiLWZhZjQ4NDZmNzlhOSIsICJyZXBvcnRzX3RvX3NvdXJjZV9wZXJzb25faWQiOiAiMjhlYTJlNjQtNmU0YS00OTBkLTg2NzEtMGY3OWEzNzYxNmUyIn0sIHsiY3NnIjogIkNMQU02NTQ5IiwgImVtYWlsIjogImxhbWIuY2hyaXN0b3BoZXIuZEBnbWFpbC5jb20iLCAicGhvbmUiOiAiMzMwMzYwMjIwMiIsICJ0ZWNoX2lkIjogIjQ4NDMiLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiB0cnVlLCAibnRfbG9naW4iOiAiYnAtY2xhbWIxMjQiLCAiZnVsbF9uYW1lIjogIkNocmlzdG9waGVyIExhbWIiLCAicm9sZV90eXBlIjogIlRFQ0giLCAic3RhcnRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImZ1c2VfZW1wX2lkIjogIjEyNDUxMyIsICJvZmZpY2VfbmFtZSI6ICJQaXR0c2J1cmdoIiwgImlzX2xlYWRlcnNoaXAiOiBmYWxzZSwgImxvY2F0aW9uX2NvZGUiOiAiNDEwIiwgInBvc2l0aW9uX3RpdGxlIjogIlRlY2huaWNpYW4iLCAicmVwb3J0c190b19uYW1lIjogIkx1Y2FzIFdpbGxpYW1zIiwgInNvdXJjZV9wZXJzb25faWQiOiAiOGUxZGVlNzMtNDQ5Yy00MWJkLWEzOTQtMDdmYTA2ZWNmZTU3IiwgImxpbmtfcGxhdGZvcm1fb3duZXIiOiBmYWxzZSwgInNvdXJjZV9hc3NpZ25tZW50X2lkIjogImU1YjlmNjAyLWUwYTMtNGYzMC05ZmRiLTM3ZjUzZmQ1ODQ4YSIsICJyZXBvcnRzX3RvX3NvdXJjZV9wZXJzb25faWQiOiAiNDQzNzY3OGYtMzljOS00MzJjLWJjNDEtN2FjNjllYTJjMWE0In0sIHsiY3NnIjogbnVsbCwgImVtYWlsIjogbnVsbCwgInBob25lIjogbnVsbCwgInRlY2hfaWQiOiAiNDg5NiIsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IHRydWUsICJudF9sb2dpbiI6IG51bGwsICJmdWxsX25hbWUiOiAiRGF2aWRsZWEgV2FsdG9uIiwgInJvbGVfdHlwZSI6ICJURUNIIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6IG51bGwsICJvZmZpY2VfbmFtZSI6ICJTY3JhbnRvbiIsICJpc19sZWFkZXJzaGlwIjogZmFsc2UsICJsb2NhdGlvbl9jb2RlIjogIjQxMCIsICJwb3NpdGlvbl90aXRsZSI6ICJUZWNobmljaWFuIiwgInJlcG9ydHNfdG9fbmFtZSI6IG51bGwsICJzb3VyY2VfcGVyc29uX2lkIjogIjRiYjhiZWVhLTQ1MGMtNDA1OC05MWVlLWM5YzVjNWJkMDdmYyIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICI5MzJhMTAwZi1jYjk3LTRkM2QtODc1OS1hNDI2MWVmY2E2ZjkiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogbnVsbH0sIHsiY3NnIjogbnVsbCwgImVtYWlsIjogInJyb3NzaUBpdGdjb21tLmNvbSIsICJwaG9uZSI6ICI3ODY1MDkwNjI5IiwgInRlY2hfaWQiOiBudWxsLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiBmYWxzZSwgIm50X2xvZ2luIjogbnVsbCwgImZ1bGxfbmFtZSI6ICJIYXJyaXNidXJnIFtSUl0iLCAicm9sZV90eXBlIjogIk1BTkFHRVIiLCAic3RhcnRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImZ1c2VfZW1wX2lkIjogIjEwNDMxNiIsICJvZmZpY2VfbmFtZSI6ICJIYXJyaXNidXJnIiwgImlzX2xlYWRlcnNoaXAiOiB0cnVlLCAibG9jYXRpb25fY29kZSI6ICI0MTAiLCAicG9zaXRpb25fdGl0bGUiOiAiUHJvamVjdCBNYW5hZ2VyIiwgInJlcG9ydHNfdG9fbmFtZSI6ICJMdWNhcyBXaWxsaWFtcyIsICJzb3VyY2VfcGVyc29uX2lkIjogIjI4ZWEyZTY0LTZlNGEtNDkwZC04NjcxLTBmNzlhMzc2MTZlMiIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICJlNThkMGZhNS01MjBiLTRiZWItYmMyMS0zYzU3MTVlYjk1MjciLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogIjQ0Mzc2NzhmLTM5YzktNDMyYy1iYzQxLTdhYzY5ZWEyYzFhNCJ9LCB7ImNzZyI6ICJKWU9VOTA3MSIsICJlbWFpbCI6ICJKYXRoYW41NDMyMUBnbWFpbC5jb20iLCAicGhvbmUiOiAiODE0NDE0MTgzMyIsICJ0ZWNoX2lkIjogIjQ3NjgiLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiB0cnVlLCAibnRfbG9naW4iOiAiQnAtanlvdW5nNDkzIiwgImZ1bGxfbmFtZSI6ICJKYXRoYW4gWW91bmciLCAicm9sZV90eXBlIjogIlRFQ0giLCAic3RhcnRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImZ1c2VfZW1wX2lkIjogIjEwMjIxMyIsICJvZmZpY2VfbmFtZSI6ICJIYXJyaXNidXJnIiwgImlzX2xlYWRlcnNoaXAiOiBmYWxzZSwgImxvY2F0aW9uX2NvZGUiOiAiNDEwIiwgInBvc2l0aW9uX3RpdGxlIjogIlRlY2huaWNpYW4iLCAicmVwb3J0c190b19uYW1lIjogIkhhcnJpc2J1cmcgW1JSXSIsICJzb3VyY2VfcGVyc29uX2lkIjogImU5OGZhYzIxLTE5ZDQtNDUxNi1iMDk1LWM0ODRkNDg5NDQyMiIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICIzZDlkN2U2Mi00YmQxLTQwNGYtODcxYy1lYWM3MGVkYTNlNmIiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogIjI4ZWEyZTY0LTZlNGEtNDkwZC04NjcxLTBmNzlhMzc2MTZlMiJ9LCB7ImNzZyI6ICJKQk9SOTExMCIsICJlbWFpbCI6ICJtYWl0cmV6YXpvb0BvdXRsb29rLmNvbSIsICJwaG9uZSI6ICI1MDkyNzAwMjcwIiwgInRlY2hfaWQiOiAiNDc3MyIsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IHRydWUsICJudF9sb2dpbiI6ICJCcC1qYm9yZGU5MzUiLCAiZnVsbF9uYW1lIjogIkppbW1pdHJlZSBCb3JkZXMiLCAicm9sZV90eXBlIjogIlRFQ0giLCAic3RhcnRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImZ1c2VfZW1wX2lkIjogIjEyMzg1OSIsICJvZmZpY2VfbmFtZSI6ICJIYXJyaXNidXJnIiwgImlzX2xlYWRlcnNoaXAiOiBmYWxzZSwgImxvY2F0aW9uX2NvZGUiOiAiNDEwIiwgInBvc2l0aW9uX3RpdGxlIjogIlRlY2huaWNpYW4iLCAicmVwb3J0c190b19uYW1lIjogIkhhcnJpc2J1cmcgW1JSXSIsICJzb3VyY2VfcGVyc29uX2lkIjogIjgzZTkzZTllLWYyYWItNGU4ZS1hYTE1LWM2NzUwYzNjMmFkMCIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICIzYmU4MmQ4ZC04OGUwLTQ3OWEtYjNlNy1hZGI2OGE3MTk0YjciLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogIjI4ZWEyZTY0LTZlNGEtNDkwZC04NjcxLTBmNzlhMzc2MTZlMiJ9LCB7ImNzZyI6ICJKQlVSNDM0NyIsICJlbWFpbCI6ICJncjhmbGRhZEBjb21jYXN0Lm5ldCIsICJwaG9uZSI6ICI0MTIzOTA5MjMxIiwgInRlY2hfaWQiOiAiNDg1OCIsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IHRydWUsICJudF9sb2dpbiI6ICJCcC1qYnVyZ2gxOTMiLCAiZnVsbF9uYW1lIjogIkpvaG4gQnVyZ2hhcmR0IiwgInJvbGVfdHlwZSI6ICJURUNIIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6ICIxMjcxMTMiLCAib2ZmaWNlX25hbWUiOiAiUGl0dHNidXJnaCIsICJpc19sZWFkZXJzaGlwIjogZmFsc2UsICJsb2NhdGlvbl9jb2RlIjogIjQxMCIsICJwb3NpdGlvbl90aXRsZSI6ICJUZWNobmljaWFuIiwgInJlcG9ydHNfdG9fbmFtZSI6ICJMdWNhcyBXaWxsaWFtcyIsICJzb3VyY2VfcGVyc29uX2lkIjogImU2ZDFlYWFmLTY2ZDktNDU3NS1hZTVlLTQxYmIyNjYzNzRlMCIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICJkMDJjNDM5Ni0wM2Q1LTQ2YTItYTMzMC0wOGM2OWZkOThhOGEiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogIjQ0Mzc2NzhmLTM5YzktNDMyYy1iYzQxLTdhYzY5ZWEyYzFhNCJ9LCB7ImNzZyI6IG51bGwsICJlbWFpbCI6ICJKZXZhbnNAaXRnY29tbS5jb20iLCAicGhvbmUiOiAiNTcwOTIxMjUzNCIsICJ0ZWNoX2lkIjogbnVsbCwgImVuZF9kYXRlIjogbnVsbCwgImlzX2ZpZWxkIjogZmFsc2UsICJudF9sb2dpbiI6IG51bGwsICJmdWxsX25hbWUiOiAiSm9obiBFdmFucyIsICJyb2xlX3R5cGUiOiAiU1VQRVJWSVNPUiIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiMTI0MTkzIiwgIm9mZmljZV9uYW1lIjogIlNjcmFudG9uIiwgImlzX2xlYWRlcnNoaXAiOiB0cnVlLCAibG9jYXRpb25fY29kZSI6ICI0MTAiLCAicG9zaXRpb25fdGl0bGUiOiAiSVRHIFN1cGVydmlzb3IiLCAicmVwb3J0c190b19uYW1lIjogIkx1Y2FzIFdpbGxpYW1zIiwgInNvdXJjZV9wZXJzb25faWQiOiAiNjFkNDY3YzEtYjAyOC00ZGNhLWIyYTQtMmVhZmI4MWViMTFiIiwgImxpbmtfcGxhdGZvcm1fb3duZXIiOiBmYWxzZSwgInNvdXJjZV9hc3NpZ25tZW50X2lkIjogIjI0NmEzMGFkLWQzNzUtNDNlNi1iN2Y2LWE2MzdkMjQ0OWZiMSIsICJyZXBvcnRzX3RvX3NvdXJjZV9wZXJzb25faWQiOiAiNDQzNzY3OGYtMzljOS00MzJjLWJjNDEtN2FjNjllYTJjMWE0In0sIHsiY3NnIjogIkxXSUw2Njg3IiwgImVtYWlsIjogIkxlcnJpY2tkdzE4QGdtYWlsLmNvbSIsICJwaG9uZSI6ICI0MTI3MzUwNzUyIiwgInRlY2hfaWQiOiAiNDc1NiIsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IHRydWUsICJudF9sb2dpbiI6ICJicC1sd2lsbGk3NDMiLCAiZnVsbF9uYW1lIjogIkxlcnJpY2sgV2lsbGlhbXMiLCAicm9sZV90eXBlIjogIlRFQ0giLCAic3RhcnRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImZ1c2VfZW1wX2lkIjogIjEwMzUyNiIsICJvZmZpY2VfbmFtZSI6ICJQaXR0c2J1cmdoIiwgImlzX2xlYWRlcnNoaXAiOiBmYWxzZSwgImxvY2F0aW9uX2NvZGUiOiAiNDEwIiwgInBvc2l0aW9uX3RpdGxlIjogIlRlY2huaWNpYW4iLCAicmVwb3J0c190b19uYW1lIjogIkx1Y2FzIFdpbGxpYW1zIiwgInNvdXJjZV9wZXJzb25faWQiOiAiODA4M2YwNzAtYmMzNS00ZDdiLWI4ZDQtNDNhYzVmZTAyZmU3IiwgImxpbmtfcGxhdGZvcm1fb3duZXIiOiBmYWxzZSwgInNvdXJjZV9hc3NpZ25tZW50X2lkIjogImIzMzU5MDQ2LTI5NTktNGE1Ny04OWUyLTMxYzA4MDRmMTJlMiIsICJyZXBvcnRzX3RvX3NvdXJjZV9wZXJzb25faWQiOiAiNDQzNzY3OGYtMzljOS00MzJjLWJjNDEtN2FjNjllYTJjMWE0In0sIHsiY3NnIjogbnVsbCwgImVtYWlsIjogImx3aWxsaWFtc0BpdGdjb21tLmNvbSIsICJwaG9uZSI6ICI0MTI2MTM3MjAxIiwgInRlY2hfaWQiOiBudWxsLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiBmYWxzZSwgIm50X2xvZ2luIjogbnVsbCwgImZ1bGxfbmFtZSI6ICJMdWNhcyBXaWxsaWFtcyIsICJyb2xlX3R5cGUiOiAiTUFOQUdFUiIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiMTI2NTMwIiwgIm9mZmljZV9uYW1lIjogIlBpdHRzYnVyZ2giLCAiaXNfbGVhZGVyc2hpcCI6IHRydWUsICJsb2NhdGlvbl9jb2RlIjogIjQxMCIsICJwb3NpdGlvbl90aXRsZSI6ICJSZWdpb25hbCBNYW5hZ2VyIiwgInJlcG9ydHNfdG9fbmFtZSI6ICJUZWQgQ2FybHNvbiIsICJzb3VyY2VfcGVyc29uX2lkIjogIjQ0Mzc2NzhmLTM5YzktNDMyYy1iYzQxLTdhYzY5ZWEyYzFhNCIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICIxNDQ2NDdhOC0wZGMzLTQ5M2YtOGM1Zi01ZGQwOWU2MmQ2ODEiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogIjVjYWFlYzJlLWIwODMtNDcxNC1iMTdlLWY4OTcwMWRlMzM5OSJ9LCB7ImNzZyI6ICJSU1RBNDQxNCIsICJlbWFpbCI6ICJyZ3M0MTU0MTVAZ21haWwuY29tIiwgInBob25lIjogIjYxNTU5NjcyMTQiLCAidGVjaF9pZCI6ICI0NzU1IiwgImVuZF9kYXRlIjogbnVsbCwgImlzX2ZpZWxkIjogdHJ1ZSwgIm50X2xvZ2luIjogIkJwLXJzdGFtcDAwMiIsICJmdWxsX25hbWUiOiAiUm9kbmV5IFN0YW1wcyIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiMTA1OTQwIiwgIm9mZmljZV9uYW1lIjogIlNjcmFudG9uIiwgImlzX2xlYWRlcnNoaXAiOiBmYWxzZSwgImxvY2F0aW9uX2NvZGUiOiAiNDEwIiwgInBvc2l0aW9uX3RpdGxlIjogIlRlY2huaWNpYW4iLCAicmVwb3J0c190b19uYW1lIjogIkpvaG4gRXZhbnMiLCAic291cmNlX3BlcnNvbl9pZCI6ICI1MWYwYzI0Yi0yM2UzLTQxMjktYTRiMS0yNDUyODVmMmQzMjMiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiYzYwNDgwMzktZjE3OC00ZGY3LTg4ZTItYzYxMzJjZmM4M2E2IiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICI2MWQ0NjdjMS1iMDI4LTRkY2EtYjJhNC0yZWFmYjgxZWIxMWIifSwgeyJjc2ciOiAiV0JVUjU5OTEiLCAiZW1haWwiOiAiYmlsbGNyeXN0YWwwN0BnbWFpbC5jb20iLCAicGhvbmUiOiAiNDEyNDYzMTE0OCIsICJ0ZWNoX2lkIjogIjQ3NzUiLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiB0cnVlLCAibnRfbG9naW4iOiAiQnAtd2J1cmdoNjEzIiwgImZ1bGxfbmFtZSI6ICJXaWxsaWFtIEJ1cmdoYXJkdCIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiMTIzNzI0IiwgIm9mZmljZV9uYW1lIjogIlBpdHRzYnVyZ2giLCAiaXNfbGVhZGVyc2hpcCI6IGZhbHNlLCAibG9jYXRpb25fY29kZSI6ICI0MTAiLCAicG9zaXRpb25fdGl0bGUiOiAiVGVjaG5pY2lhbiIsICJyZXBvcnRzX3RvX25hbWUiOiAiTHVjYXMgV2lsbGlhbXMiLCAic291cmNlX3BlcnNvbl9pZCI6ICI5M2E2ODBhZC02MDFjLTQxZDUtODE5Zi1mNmUyYzMxNmYxYmMiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiNmQ2ZTJmYWMtNzRlNy00MGEwLWIxZDEtZDRhZjU1NGMyNGRmIiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICI0NDM3Njc4Zi0zOWM5LTQzMmMtYmM0MS03YWM2OWVhMmMxYTQifSwgeyJjc2ciOiAiQU1JQzc1MjgiLCAiZW1haWwiOiAiYW1pY2hlbEBpdGdjb21tLmNvbSIsICJwaG9uZSI6ICI2MDk0MDQ4MzMwIiwgInRlY2hfaWQiOiAiNzI5NiIsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IHRydWUsICJudF9sb2dpbiI6ICJicC1hbWljaGU4ODkiLCAiZnVsbF9uYW1lIjogIkFkYW0gUGV0ZXIgTWljaGVsIiwgInJvbGVfdHlwZSI6ICJURUNIIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6ICI3MDAwMTYiLCAib2ZmaWNlX25hbWUiOiAiRWdnIEhhcmJvciIsICJpc19sZWFkZXJzaGlwIjogZmFsc2UsICJsb2NhdGlvbl9jb2RlIjogIjQyNyIsICJwb3NpdGlvbl90aXRsZSI6ICJUZWNobmljaWFuIiwgInJlcG9ydHNfdG9fbmFtZSI6ICJMYXdyZW5jZSBKIFNjb3R0IEpyLiIsICJzb3VyY2VfcGVyc29uX2lkIjogIjdiOTlkYjUxLWVhYjQtNGVhZi04ZTU1LTA5OWViM2Q2NTMxOCIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICI2NTY3NmEyYi1iZjA4LTRkM2MtYWYyNy02MzQyZTE2MGVmMjYiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogIjk3ZTVlOGM4LTA2YzYtNDMxMy1iNmUxLWQ0NDYyM2MwMDE5YyJ9LCB7ImNzZyI6ICJDTVVMMTExMSIsICJlbWFpbCI6ICJDaHJpc211bGhlcm4zMUBnbWFpbC5jb20iLCAicGhvbmUiOiAiNjA5MjA0ODU0OCIsICJ0ZWNoX2lkIjogIjcyMzUiLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiB0cnVlLCAibnRfbG9naW4iOiAiYnAtY211bGhlODg2IiwgImZ1bGxfbmFtZSI6ICJDaHJpc3RvcGhlciBMZWUgTXVsaGVybiIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiNzAwMDM5IiwgIm9mZmljZV9uYW1lIjogIkVnZyBIYXJib3IiLCAiaXNfbGVhZGVyc2hpcCI6IGZhbHNlLCAibG9jYXRpb25fY29kZSI6ICI0MjciLCAicG9zaXRpb25fdGl0bGUiOiAiVGVjaG5pY2lhbiIsICJyZXBvcnRzX3RvX25hbWUiOiAiTGF3cmVuY2UgSiBTY290dCBKci4iLCAic291cmNlX3BlcnNvbl9pZCI6ICI2YmRkZDYzNC0wZmY3LTQzNzItODdiMy1iMWQyZWJmYTg0NTIiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiZjgxZjFmNTYtMGY2My00NWUzLTkxY2QtOWJmNjNmZWYxMTI0IiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICI5N2U1ZThjOC0wNmM2LTQzMTMtYjZlMS1kNDQ2MjNjMDAxOWMifSwgeyJjc2ciOiAiQ01DQzc0NzciLCAiZW1haWwiOiAiY21jY2FudHNAaXRnY29tbS5jb20iLCAicGhvbmUiOiAiOTczNjA3NjY0NSIsICJ0ZWNoX2lkIjogIjc1NzMiLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiB0cnVlLCAibnRfbG9naW4iOiAiYnAtY21jY2FuNzEzIiwgImZ1bGxfbmFtZSI6ICJDbGVhdm9uIE1jY2FudHMiLCAicm9sZV90eXBlIjogIlRFQ0giLCAic3RhcnRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImZ1c2VfZW1wX2lkIjogIjcwMDAwNSIsICJvZmZpY2VfbmFtZSI6ICJFZGlzb24iLCAiaXNfbGVhZGVyc2hpcCI6IGZhbHNlLCAibG9jYXRpb25fY29kZSI6ICI0MjciLCAicG9zaXRpb25fdGl0bGUiOiAiVGVjaG5pY2lhbiIsICJyZXBvcnRzX3RvX25hbWUiOiAiRnJpdHogRiBGcmFnZSIsICJzb3VyY2VfcGVyc29uX2lkIjogImI3YzExNmE3LWYwNjEtNDYyMS1iZjI3LWVmNzE4OTcxZThhYyIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICI4MjA1YjQ2ZS01MzMwLTQ1MTAtYWJmYi1mYjVlZTUxMGY0YmQiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogImY2MTRiYTU4LWY0YjItNDUyOC1hMjMyLWQwNzA4NzZmYTc3ZSJ9LCB7ImNzZyI6ICJEQlJPNzQxMSIsICJlbWFpbCI6ICJkYWJyb3duQGl0Z2NvbW0uY29tIiwgInBob25lIjogIjkwODc2NDc4MzkiLCAidGVjaF9pZCI6ICI3NTM5IiwgImVuZF9kYXRlIjogbnVsbCwgImlzX2ZpZWxkIjogdHJ1ZSwgIm50X2xvZ2luIjogImJwLWRicm93bjI3OCIsICJmdWxsX25hbWUiOiAiRGFtaWFuIFZhbGVudGluaXVzIEJyb3duIiwgInJvbGVfdHlwZSI6ICJURUNIIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6ICI3MDAwMjUiLCAib2ZmaWNlX25hbWUiOiAiRWRpc29uIiwgImlzX2xlYWRlcnNoaXAiOiBmYWxzZSwgImxvY2F0aW9uX2NvZGUiOiAiNDI3IiwgInBvc2l0aW9uX3RpdGxlIjogIlRlY2huaWNpYW4iLCAicmVwb3J0c190b19uYW1lIjogIkZyaXR6IEYgRnJhZ2UiLCAic291cmNlX3BlcnNvbl9pZCI6ICJiODlkY2M3YS04MDU4LTQxNGUtOTU1OS0yNDk0NzgyZjg1NTkiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiNjMxN2RlZDUtMDU3Yy00MmM4LTk3MTctYzJkNGJmOTE5ZmVlIiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICJmNjE0YmE1OC1mNGIyLTQ1MjgtYTIzMi1kMDcwODc2ZmE3N2UifSwgeyJjc2ciOiAiRE1PTjc1MzAiLCAiZW1haWwiOiAiZG1vbnRnb21lcnlAaXRnY29tbS5jb20iLCAicGhvbmUiOiAiMjE1ODI3OTE2MyIsICJ0ZWNoX2lkIjogIjc1MDkiLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiB0cnVlLCAibnRfbG9naW4iOiAiYnAtZG1vbnRnMDAyIiwgImZ1bGxfbmFtZSI6ICJEYXJyZW4gTWF1cmljZSBNb250Z29tZXJ5IiwgInJvbGVfdHlwZSI6ICJURUNIIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6ICI3MDAwNTIiLCAib2ZmaWNlX25hbWUiOiAiRWRpc29uIiwgImlzX2xlYWRlcnNoaXAiOiBmYWxzZSwgImxvY2F0aW9uX2NvZGUiOiAiNDI3IiwgInBvc2l0aW9uX3RpdGxlIjogIlRlY2huaWNpYW4iLCAicmVwb3J0c190b19uYW1lIjogIk5ha2FzaCBMbGV3ZWxseW4iLCAic291cmNlX3BlcnNvbl9pZCI6ICJlZDhkYzcwNC0wNDI1LTQ3MDItYjM4Yi1hYjZmMWU0OTIzYjIiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiMDU0YzJkODktOTRmNS00MmFmLWE5NWYtNjY1ZGM0ZWQ0MzBkIiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICI5MDE2MWQ1Ni00ZTc3LTQ4NDktYTFkZS1kM2Q3NDE2Y2MwMzcifSwgeyJjc2ciOiAiREVDSDc0MjgiLCAiZW1haWwiOiAiZGVjaGV2ZXJyaWFAaXRnY29tbS5jb20iLCAicGhvbmUiOiAiOTA4NDIyNTAwMSIsICJ0ZWNoX2lkIjogIjc1NTEiLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiB0cnVlLCAibnRfbG9naW4iOiAiYnAtZGVjaGV2NzA2IiwgImZ1bGxfbmFtZSI6ICJEYXZpZCBBIEVjaGV2ZXJyaWEiLCAicm9sZV90eXBlIjogIlRFQ0giLCAic3RhcnRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImZ1c2VfZW1wX2lkIjogIjcwMDEwMiIsICJvZmZpY2VfbmFtZSI6ICJFZGlzb24iLCAiaXNfbGVhZGVyc2hpcCI6IGZhbHNlLCAibG9jYXRpb25fY29kZSI6ICI0MjciLCAicG9zaXRpb25fdGl0bGUiOiAiVGVjaG5pY2lhbiIsICJyZXBvcnRzX3RvX25hbWUiOiAiRnJpdHogRiBGcmFnZSIsICJzb3VyY2VfcGVyc29uX2lkIjogIjMwMDU1ZDVhLWNjNWEtNDM2Zi1hMzllLWRmMjY1NzlmOWQxZiIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICJjNzIyMzc5Ny1iNGE2LTRiNGEtOTE5Ny0yYTI5MDlkMDFmNWYiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogImY2MTRiYTU4LWY0YjItNDUyOC1hMjMyLWQwNzA4NzZmYTc3ZSJ9LCB7ImNzZyI6ICJETUlMMTQzMyIsICJlbWFpbCI6ICJkbWlsbGVyQGl0Z2NvbW0uY29tIiwgInBob25lIjogIjYwOTI4OTU1NzYiLCAidGVjaF9pZCI6ICI3NTk5IiwgImVuZF9kYXRlIjogbnVsbCwgImlzX2ZpZWxkIjogdHJ1ZSwgIm50X2xvZ2luIjogImJwLWRtaWxsZTM3OSIsICJmdWxsX25hbWUiOiAiRGV2aW4gRG91Z2xhcyBNaWxsZXIiLCAicm9sZV90eXBlIjogIlRFQ0giLCAic3RhcnRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImZ1c2VfZW1wX2lkIjogIjcwMDE1NSIsICJvZmZpY2VfbmFtZSI6ICJFZ2cgSGFyYm9yIiwgImlzX2xlYWRlcnNoaXAiOiBmYWxzZSwgImxvY2F0aW9uX2NvZGUiOiAiNDI3IiwgInBvc2l0aW9uX3RpdGxlIjogIlRlY2huaWNpYW4iLCAicmVwb3J0c190b19uYW1lIjogIk5ha2FzaCBMbGV3ZWxseW4iLCAic291cmNlX3BlcnNvbl9pZCI6ICJjNjk1YjM3Ny0wNDM0LTQzMzUtOWEwYy1lN2ViNjAyNWExZTIiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiNjkxODhhMzEtZjM0MC00NWMwLWFkYjMtOTMyNzI1MjExNTMzIiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICI5MDE2MWQ1Ni00ZTc3LTQ4NDktYTFkZS1kM2Q3NDE2Y2MwMzcifSwgeyJjc2ciOiAiRU9GTzc1MzIiLCAiZW1haWwiOiAieWF3XzIyMkB5YWhvby5jb20iLCAicGhvbmUiOiAiNjA5NTgwOTE5NyIsICJ0ZWNoX2lkIjogIjc1ODEiLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiB0cnVlLCAibnRfbG9naW4iOiAiYnAtZW9mb3N1NjM2IiwgImZ1bGxfbmFtZSI6ICJFbW1hbnVlbCBLd2FrdSBPZm9zdSIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiNzAwMTUyIiwgIm9mZmljZV9uYW1lIjogIkVkaXNvbiIsICJpc19sZWFkZXJzaGlwIjogZmFsc2UsICJsb2NhdGlvbl9jb2RlIjogIjQyNyIsICJwb3NpdGlvbl90aXRsZSI6ICJUZWNobmljaWFuIiwgInJlcG9ydHNfdG9fbmFtZSI6ICJGcml0eiBGIEZyYWdlIiwgInNvdXJjZV9wZXJzb25faWQiOiAiMGE0ODAzZjgtYTRjYi00Njk1LWFjOTEtMjk2ODU5YWJmMTE0IiwgImxpbmtfcGxhdGZvcm1fb3duZXIiOiBmYWxzZSwgInNvdXJjZV9hc3NpZ25tZW50X2lkIjogImU5ZmU5MzYxLTYyMzktNGIzOC04ZTUwLTRiZmE3OThiZmY0YSIsICJyZXBvcnRzX3RvX3NvdXJjZV9wZXJzb25faWQiOiAiZjYxNGJhNTgtZjRiMi00NTI4LWEyMzItZDA3MDg3NmZhNzdlIn0sIHsiY3NnIjogbnVsbCwgImVtYWlsIjogImZmcmFnZUBpdGdjb21tLmNvbSIsICJwaG9uZSI6ICI5MDg0ODUwNTY0IiwgInRlY2hfaWQiOiBudWxsLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiBmYWxzZSwgIm50X2xvZ2luIjogbnVsbCwgImZ1bGxfbmFtZSI6ICJGcml0eiBGIEZyYWdlIiwgInJvbGVfdHlwZSI6ICJTVVBFUlZJU09SIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6ICI3MDAwNzgiLCAib2ZmaWNlX25hbWUiOiAiRWRpc29uIiwgImlzX2xlYWRlcnNoaXAiOiB0cnVlLCAibG9jYXRpb25fY29kZSI6ICI0MjciLCAicG9zaXRpb25fdGl0bGUiOiAiSVRHIFN1cGVydmlzb3IiLCAicmVwb3J0c190b19uYW1lIjogIkdlb3JnZSBLb2VsbGUiLCAic291cmNlX3BlcnNvbl9pZCI6ICJmNjE0YmE1OC1mNGIyLTQ1MjgtYTIzMi1kMDcwODc2ZmE3N2UiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiMTIzMjQwMTItMTNjMC00ZTk5LTkzMmEtNzNmOWRhMGE1ZjUyIiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICI0YjU2NGEzMC03YjkwLTRhMTEtOTQ2MS1iZmZkYjg1MTE5MzMifSwgeyJjc2ciOiAiR0tPRTc0NjYiLCAiZW1haWwiOiAiZ2tvZWxsZWl2QGl0Z2NvbW0uY29tIiwgInBob25lIjogIjYwOTgyNzcwMDAiLCAidGVjaF9pZCI6IG51bGwsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IGZhbHNlLCAibnRfbG9naW4iOiAiYnAtZ2tvZWxsMzk1IiwgImZ1bGxfbmFtZSI6ICJHZW9yZ2UgS29lbGxlIiwgInJvbGVfdHlwZSI6ICJNQU5BR0VSIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6ICI3MDAzMjQiLCAib2ZmaWNlX25hbWUiOiBudWxsLCAiaXNfbGVhZGVyc2hpcCI6IHRydWUsICJsb2NhdGlvbl9jb2RlIjogIjQyNyIsICJwb3NpdGlvbl90aXRsZSI6ICJSZWdpb25hbCBNYW5hZ2VyIiwgInJlcG9ydHNfdG9fbmFtZSI6IG51bGwsICJzb3VyY2VfcGVyc29uX2lkIjogIjRiNTY0YTMwLTdiOTAtNGExMS05NDYxLWJmZmRiODUxMTkzMyIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICI0MWZjMTUzNC1iMDE1LTRmN2EtYWZmNy1kZGUzMWMxZjE4OWEiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogbnVsbH0sIHsiY3NnIjogIklLQU0wMzUxIiwgImVtYWlsIjogImlrYW1hcmFAaXRnY29tbS5jb20iLCAicGhvbmUiOiAiODU2NzM5NzI2MiIsICJ0ZWNoX2lkIjogIjcxMjkiLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiB0cnVlLCAibnRfbG9naW4iOiAiYnAtaWthbWFyODIzIiwgImZ1bGxfbmFtZSI6ICJJYnJhaGltIFJhaGltIEthbWFyYSIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiMTIxNDM5IiwgIm9mZmljZV9uYW1lIjogIkVnZyBIYXJib3IiLCAiaXNfbGVhZGVyc2hpcCI6IGZhbHNlLCAibG9jYXRpb25fY29kZSI6ICI0MjciLCAicG9zaXRpb25fdGl0bGUiOiAiVGVjaG5pY2lhbiIsICJyZXBvcnRzX3RvX25hbWUiOiAiTmFrYXNoIExsZXdlbGx5biIsICJzb3VyY2VfcGVyc29uX2lkIjogImZlZTQ1NDQzLTliNWUtNDNkMS05MzJhLTIzZTYxYTZiNWUzNyIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICI5MTZiNDQ4NC1hMjMyLTQyNDktYmEyYS02ZDM5N2FhNzFkMmMiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogIjkwMTYxZDU2LTRlNzctNDg0OS1hMWRlLWQzZDc0MTZjYzAzNyJ9LCB7ImNzZyI6ICJKTUJBMDUxMSIsICJlbWFpbCI6ICJqbWJhbmVAaXRnY29tbS5jb20iLCAicGhvbmUiOiAiNjA5MzQ2MTcwMSIsICJ0ZWNoX2lkIjogIjc1NzIiLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiB0cnVlLCAibnRfbG9naW4iOiAiYnAtam1iYW5lMTIzIiwgImZ1bGxfbmFtZSI6ICJKYWNvYiBNYmFuZSIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiNzAwMTI5IiwgIm9mZmljZV9uYW1lIjogIkVnZyBIYXJib3IiLCAiaXNfbGVhZGVyc2hpcCI6IGZhbHNlLCAibG9jYXRpb25fY29kZSI6ICI0MjciLCAicG9zaXRpb25fdGl0bGUiOiAiVGVjaG5pY2lhbiIsICJyZXBvcnRzX3RvX25hbWUiOiAiTmFrYXNoIExsZXdlbGx5biIsICJzb3VyY2VfcGVyc29uX2lkIjogImQxM2Y2MmEyLWJjMTYtNDZkMy04NjJiLTU1MGJjNGQ4ZmY4ZCIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICJkYzViODEwMC05YzQ3LTQ2YjMtYjAzZS1jMTg3Y2E3ZmNhOTMiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogIjkwMTYxZDU2LTRlNzctNDg0OS1hMWRlLWQzZDc0MTZjYzAzNyJ9LCB7ImNzZyI6ICJKREVMOTI1NSIsICJlbWFpbCI6ICJqZGVsYW5leUBpdGdjb21tLmNvbSIsICJwaG9uZSI6ICIyNTMzMzczNTA2IiwgInRlY2hfaWQiOiAiNzA0OCIsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IHRydWUsICJudF9sb2dpbiI6ICJicC1qZGVsYW4xNDgiLCAiZnVsbF9uYW1lIjogIkphbWVzIFBhdWwgRGVsYW5leSIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiMTI2MTYzIiwgIm9mZmljZV9uYW1lIjogIkVnZyBIYXJib3IiLCAiaXNfbGVhZGVyc2hpcCI6IGZhbHNlLCAibG9jYXRpb25fY29kZSI6ICI0MjciLCAicG9zaXRpb25fdGl0bGUiOiAiVGVjaG5pY2lhbiIsICJyZXBvcnRzX3RvX25hbWUiOiAiTGF3cmVuY2UgSiBTY290dCBKci4iLCAic291cmNlX3BlcnNvbl9pZCI6ICIwMWJlYmUzMy05MDg3LTRlNWItODMyNS1mZjA0YTRkNmJjY2UiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiMmI2MGRjOTAtZmFkMy00YjhlLTkyMmYtODQyNjBmNmVhZWY4IiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICI5N2U1ZThjOC0wNmM2LTQzMTMtYjZlMS1kNDQ2MjNjMDAxOWMifSwgeyJjc2ciOiBudWxsLCAiZW1haWwiOiAibHNjb3R0QGl0Z2NvbW0uY29tIiwgInBob25lIjogIjg1NjM2NDE4NDUiLCAidGVjaF9pZCI6IG51bGwsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IGZhbHNlLCAibnRfbG9naW4iOiBudWxsLCAiZnVsbF9uYW1lIjogIkxhd3JlbmNlIEogU2NvdHQgSnIuIiwgInJvbGVfdHlwZSI6ICJTVVBFUlZJU09SIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6ICI3MDAwMzEiLCAib2ZmaWNlX25hbWUiOiAiRWdnIEhhcmJvciIsICJpc19sZWFkZXJzaGlwIjogdHJ1ZSwgImxvY2F0aW9uX2NvZGUiOiAiNDI3IiwgInBvc2l0aW9uX3RpdGxlIjogIklURyBTdXBlcnZpc29yIiwgInJlcG9ydHNfdG9fbmFtZSI6ICJHZW9yZ2UgS29lbGxlIiwgInNvdXJjZV9wZXJzb25faWQiOiAiOTdlNWU4YzgtMDZjNi00MzEzLWI2ZTEtZDQ0NjIzYzAwMTljIiwgImxpbmtfcGxhdGZvcm1fb3duZXIiOiBmYWxzZSwgInNvdXJjZV9hc3NpZ25tZW50X2lkIjogImE4MzI2Y2VkLTI5M2MtNDg5Zi04MjM3LTY2Y2RjMmY0MDdhYiIsICJyZXBvcnRzX3RvX3NvdXJjZV9wZXJzb25faWQiOiAiNGI1NjRhMzAtN2I5MC00YTExLTk0NjEtYmZmZGI4NTExOTMzIn0sIHsiY3NnIjogbnVsbCwgImVtYWlsIjogImx3ZWxjaEBpdGdjb21tLmNvbSIsICJwaG9uZSI6ICI2MDk0MDI3MDM1IiwgInRlY2hfaWQiOiBudWxsLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiBmYWxzZSwgIm50X2xvZ2luIjogbnVsbCwgImZ1bGxfbmFtZSI6ICJMdWtlIFIgV2VsY2giLCAicm9sZV90eXBlIjogIlNVUEVSVklTT1IiLCAic3RhcnRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImZ1c2VfZW1wX2lkIjogIjcwMDMwOSIsICJvZmZpY2VfbmFtZSI6ICJFZ2cgSGFyYm9yIiwgImlzX2xlYWRlcnNoaXAiOiB0cnVlLCAibG9jYXRpb25fY29kZSI6ICI0MjciLCAicG9zaXRpb25fdGl0bGUiOiAiSVRHIFN1cGVydmlzb3IiLCAicmVwb3J0c190b19uYW1lIjogIkdlb3JnZSBLb2VsbGUiLCAic291cmNlX3BlcnNvbl9pZCI6ICI3YTFhODdiYi1hM2EyLTQxZTYtYTFlNS1jMzY0YmE3YjI5YmUiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiYWY1N2I0ZTEtMDlkZC00MDRiLWJkNmEtNDExZTNmYmQzMGNiIiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICI0YjU2NGEzMC03YjkwLTRhMTEtOTQ2MS1iZmZkYjg1MTE5MzMifSwgeyJjc2ciOiAiTUFVUzc0MDciLCAiZW1haWwiOiAibWF1c2J5QGl0Z2NvbW0uY29tIiwgInBob25lIjogIjg1NjQwNTU0MDEiLCAidGVjaF9pZCI6ICI3NDAzIiwgImVuZF9kYXRlIjogbnVsbCwgImlzX2ZpZWxkIjogdHJ1ZSwgIm50X2xvZ2luIjogImJwLW1hdXNieTUzMCIsICJmdWxsX25hbWUiOiAiTWFrYWkgVCBBdXNieSIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiNzAwMTcwIiwgIm9mZmljZV9uYW1lIjogIkVnZyBIYXJib3IiLCAiaXNfbGVhZGVyc2hpcCI6IGZhbHNlLCAibG9jYXRpb25fY29kZSI6ICI0MjciLCAicG9zaXRpb25fdGl0bGUiOiAiVGVjaG5pY2lhbiIsICJyZXBvcnRzX3RvX25hbWUiOiAiTGF3cmVuY2UgSiBTY290dCBKci4iLCAic291cmNlX3BlcnNvbl9pZCI6ICI1OGFjMTRiYy02MjQ2LTQ1OWQtOTZiYy1lMGMyZWY3NGJjYmEiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiNjFiZmFhMjQtOWVkNS00NmM5LTljOWYtOGZkY2EyMmQwZjVkIiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICI5N2U1ZThjOC0wNmM2LTQzMTMtYjZlMS1kNDQ2MjNjMDAxOWMifSwgeyJjc2ciOiAiTVNBQTc2MTYiLCAiZW1haWwiOiAibWFuc3VyQGl0Z2NvbW0uY29tIiwgInBob25lIjogIjg1NjI1NDY0MzMiLCAidGVjaF9pZCI6ICI3NTM0IiwgImVuZF9kYXRlIjogbnVsbCwgImlzX2ZpZWxkIjogdHJ1ZSwgIm50X2xvZ2luIjogImJwLW1zYWFkMjI1IiwgImZ1bGxfbmFtZSI6ICJNYW5zdXIgQSBTYWFkIiwgInJvbGVfdHlwZSI6ICJURUNIIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6ICI3MDAxMTciLCAib2ZmaWNlX25hbWUiOiAiRWdnIEhhcmJvciIsICJpc19sZWFkZXJzaGlwIjogZmFsc2UsICJsb2NhdGlvbl9jb2RlIjogIjQyNyIsICJwb3NpdGlvbl90aXRsZSI6ICJUZWNobmljaWFuIiwgInJlcG9ydHNfdG9fbmFtZSI6ICJMYXdyZW5jZSBKIFNjb3R0IEpyLiIsICJzb3VyY2VfcGVyc29uX2lkIjogImYwNDcxMDdkLWYwMTMtNGNjOC04YmQ3LTM1YjIxMThiNjM0NyIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICIwZThmZDY0OS1iZTRjLTQwNDQtOWI1ZC1iNmY0YzZkNjIyNGEiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogIjk3ZTVlOGM4LTA2YzYtNDMxMy1iNmUxLWQ0NDYyM2MwMDE5YyJ9LCB7ImNzZyI6ICJNS0VOMTA0NiIsICJlbWFpbCI6ICJta2VubmVkeUBpdGdjb21tLmNvbSIsICJwaG9uZSI6ICIyNjcyNDI3NzYzIiwgInRlY2hfaWQiOiAiNzIwMiIsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IHRydWUsICJudF9sb2dpbiI6ICJicC1ta2VubmU2NDAiLCAiZnVsbF9uYW1lIjogIk1hdXJpY2UgVyBLZW5uZWR5IiwgInJvbGVfdHlwZSI6ICJURUNIIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6ICI3MDAxMTEiLCAib2ZmaWNlX25hbWUiOiAiRWdnIEhhcmJvciIsICJpc19sZWFkZXJzaGlwIjogZmFsc2UsICJsb2NhdGlvbl9jb2RlIjogIjQyNyIsICJwb3NpdGlvbl90aXRsZSI6ICJUZWNobmljaWFuIiwgInJlcG9ydHNfdG9fbmFtZSI6ICJOYWthc2ggTGxld2VsbHluIiwgInNvdXJjZV9wZXJzb25faWQiOiAiMTNiYzQxNGYtZWVmOC00ZGQwLWE0MGEtMjEwMTIwMzFlODA5IiwgImxpbmtfcGxhdGZvcm1fb3duZXIiOiBmYWxzZSwgInNvdXJjZV9hc3NpZ25tZW50X2lkIjogImJjYTI5YjQyLWE2NjAtNGE4OS1iYjVkLTNlM2JmZWVjNzAzMyIsICJyZXBvcnRzX3RvX3NvdXJjZV9wZXJzb25faWQiOiAiOTAxNjFkNTYtNGU3Ny00ODQ5LWExZGUtZDNkNzQxNmNjMDM3In0sIHsiY3NnIjogIk1MVUc3NDcxIiwgImVtYWlsIjogIm1sdWdlcm5lckBpdGdjb21tLmNvbSIsICJwaG9uZSI6ICI2MDk4OTI3MDM2IiwgInRlY2hfaWQiOiAiNzU0MyIsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IHRydWUsICJudF9sb2dpbiI6ICJicC1tbHVnZXIyMjgiLCAiZnVsbF9uYW1lIjogIk1pY2hhZWwgS2VubmV0aCBMdWdlcm5lciIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiNzAwMDc1IiwgIm9mZmljZV9uYW1lIjogIkVnZyBIYXJib3IiLCAiaXNfbGVhZGVyc2hpcCI6IGZhbHNlLCAibG9jYXRpb25fY29kZSI6ICI0MjciLCAicG9zaXRpb25fdGl0bGUiOiAiVGVjaG5pY2lhbiIsICJyZXBvcnRzX3RvX25hbWUiOiAiTGF3cmVuY2UgSiBTY290dCBKci4iLCAic291cmNlX3BlcnNvbl9pZCI6ICIzMDI4ODhhZC0xZjRlLTRhYzAtOGRhOS1jYzIyNDFjZWE1NGUiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiMTZkY2EzOGUtNzY0YS00MmQ4LWJlNzUtZWQwMDcxOTU0MmMyIiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICI5N2U1ZThjOC0wNmM2LTQzMTMtYjZlMS1kNDQ2MjNjMDAxOWMifSwgeyJjc2ciOiBudWxsLCAiZW1haWwiOiAibmxsZXdlbGx5bkBpdGdjb21tLmNvbSIsICJwaG9uZSI6ICI2MjkyNTE4NjU2IiwgInRlY2hfaWQiOiBudWxsLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiBmYWxzZSwgIm50X2xvZ2luIjogbnVsbCwgImZ1bGxfbmFtZSI6ICJOYWthc2ggTGxld2VsbHluIiwgInJvbGVfdHlwZSI6ICJTVVBFUlZJU09SIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6IG51bGwsICJvZmZpY2VfbmFtZSI6ICJFZGlzb24iLCAiaXNfbGVhZGVyc2hpcCI6IHRydWUsICJsb2NhdGlvbl9jb2RlIjogIjQyNyIsICJwb3NpdGlvbl90aXRsZSI6ICJJVEcgU3VwZXJ2aXNvciIsICJyZXBvcnRzX3RvX25hbWUiOiAiR2VvcmdlIEtvZWxsZSIsICJzb3VyY2VfcGVyc29uX2lkIjogIjkwMTYxZDU2LTRlNzctNDg0OS1hMWRlLWQzZDc0MTZjYzAzNyIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICIwMWQ3Y2M1OS1mNTMxLTRkY2MtOThhOS1jN2FlMWVhOGM1MmMiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogIjRiNTY0YTMwLTdiOTAtNGExMS05NDYxLWJmZmRiODUxMTkzMyJ9LCB7ImNzZyI6ICJPU0FONzUzOCIsICJlbWFpbCI6ICJvc2FudGlhZ29AaXRnY29tbS5jb20iLCAicGhvbmUiOiAiNjA5MjMzNjU3MCIsICJ0ZWNoX2lkIjogIjc1OTciLCAiZW5kX2RhdGUiOiBudWxsLCAiaXNfZmllbGQiOiB0cnVlLCAibnRfbG9naW4iOiAiYnAtb3NhbnRpNzU0IiwgImZ1bGxfbmFtZSI6ICJPY3RhdmlvIEogU2FudGlhZ28iLCAicm9sZV90eXBlIjogIlRFQ0giLCAic3RhcnRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImZ1c2VfZW1wX2lkIjogIjcwMDEzMSIsICJvZmZpY2VfbmFtZSI6ICJFZ2cgSGFyYm9yIiwgImlzX2xlYWRlcnNoaXAiOiBmYWxzZSwgImxvY2F0aW9uX2NvZGUiOiAiNDI3IiwgInBvc2l0aW9uX3RpdGxlIjogIlRlY2huaWNpYW4iLCAicmVwb3J0c190b19uYW1lIjogIk5ha2FzaCBMbGV3ZWxseW4iLCAic291cmNlX3BlcnNvbl9pZCI6ICJlNjI1MzAwMC0xNTkxLTQ0NDMtYTllOS01NGI1NGNlZjk4YjUiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiOTkwZmQ4OTYtY2E3Zi00OTM5LWE4ZTQtODZjNTQ3N2ExNmIwIiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICI5MDE2MWQ1Ni00ZTc3LTQ4NDktYTFkZS1kM2Q3NDE2Y2MwMzcifSwgeyJjc2ciOiAiUktBUjc0MzMiLCAiZW1haWwiOiAicmthcnJlckBpdGdjb21tLmNvbSIsICJwaG9uZSI6ICIyMTUyODA4NDgzIiwgInRlY2hfaWQiOiAiNzQ4MCIsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IHRydWUsICJudF9sb2dpbiI6ICJicC1ya2FycmU3NDYiLCAiZnVsbF9uYW1lIjogIlJheW1vbmQgRGFuaWVsIEthcnJlciIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiNzAwMTI4IiwgIm9mZmljZV9uYW1lIjogIkVnZyBIYXJib3IiLCAiaXNfbGVhZGVyc2hpcCI6IGZhbHNlLCAibG9jYXRpb25fY29kZSI6ICI0MjciLCAicG9zaXRpb25fdGl0bGUiOiAiVGVjaG5pY2lhbiIsICJyZXBvcnRzX3RvX25hbWUiOiAiTmFrYXNoIExsZXdlbGx5biIsICJzb3VyY2VfcGVyc29uX2lkIjogImU0ODg0YmQzLTk0MTgtNDllMS1iMjVhLTUwZjExNTgzMzE4ZiIsICJsaW5rX3BsYXRmb3JtX293bmVyIjogZmFsc2UsICJzb3VyY2VfYXNzaWdubWVudF9pZCI6ICIzZjJmZDNkMC1kYThhLTRjNWUtYmM3Mi03Njc3YWNhNzcwNzYiLCAicmVwb3J0c190b19zb3VyY2VfcGVyc29uX2lkIjogIjkwMTYxZDU2LTRlNzctNDg0OS1hMWRlLWQzZDc0MTZjYzAzNyJ9LCB7ImNzZyI6ICJSQ0FSNzgyMSIsICJlbWFpbCI6ICJyY2FyYWJhbGxvQGl0Z2NvbW0uY29tIiwgInBob25lIjogIjczMjQyNzU3NTgiLCAidGVjaF9pZCI6ICI3NTQyIiwgImVuZF9kYXRlIjogbnVsbCwgImlzX2ZpZWxkIjogdHJ1ZSwgIm50X2xvZ2luIjogImJwLXJjYXJhYjc1NCIsICJmdWxsX25hbWUiOiAiUmVtaHkgQ2FyYWJhbGxvIiwgInJvbGVfdHlwZSI6ICJURUNIIiwgInN0YXJ0X2RhdGUiOiAiMjAyNS0xMi0yMiIsICJmdXNlX2VtcF9pZCI6ICI3MDAxNjAiLCAib2ZmaWNlX25hbWUiOiAiRWRpc29uIiwgImlzX2xlYWRlcnNoaXAiOiBmYWxzZSwgImxvY2F0aW9uX2NvZGUiOiAiNDI3IiwgInBvc2l0aW9uX3RpdGxlIjogIlRlY2huaWNpYW4iLCAicmVwb3J0c190b19uYW1lIjogIkZyaXR6IEYgRnJhZ2UiLCAic291cmNlX3BlcnNvbl9pZCI6ICJhZjc3YTBlYy1iMDJhLTQ2M2YtOTI2Yi05N2ZiZmE4YWU4OWQiLCAibGlua19wbGF0Zm9ybV9vd25lciI6IGZhbHNlLCAic291cmNlX2Fzc2lnbm1lbnRfaWQiOiAiMTY1Y2IxZjAtNzY4OC00MDMyLWEyMjYtM2I2ZjMyZDZiNWFlIiwgInJlcG9ydHNfdG9fc291cmNlX3BlcnNvbl9pZCI6ICJmNjE0YmE1OC1mNGIyLTQ1MjgtYTIzMi1kMDcwODc2ZmE3N2UifSwgeyJjc2ciOiAiUkNIRTQ3OTYiLCAiZW1haWwiOiAicmNoZXJpbHVzQGl0Z2NvbW0uY29tIiwgInBob25lIjogIjI2Nzg1ODIzOTgiLCAidGVjaF9pZCI6ICI3NTQ0IiwgImVuZF9kYXRlIjogbnVsbCwgImlzX2ZpZWxkIjogdHJ1ZSwgIm50X2xvZ2luIjogImJwLXJjaGVyaTgzMyIsICJmdWxsX25hbWUiOiAiUm9ueSBDaGVyaWx1cyIsICJyb2xlX3R5cGUiOiAiVEVDSCIsICJzdGFydF9kYXRlIjogIjIwMjUtMTItMjIiLCAiZnVzZV9lbXBfaWQiOiAiMTIzMTkyIiwgIm9mZmljZV9uYW1lIjogIkVkaXNvbiIsICJpc19sZWFkZXJzaGlwIjogZmFsc2UsICJsb2NhdGlvbl9jb2RlIjogIjQyNyIsICJwb3NpdGlvbl90aXRsZSI6ICJUZWNobmljaWFuIiwgInJlcG9ydHNfdG9fbmFtZSI6ICJOYWthc2ggTGxld2VsbHluIiwgInNvdXJjZV9wZXJzb25faWQiOiAiN2I3YTFlOGItZGFhMy00MDU3LWE1NjQtMGZlZmU1ZGU4MWM3IiwgImxpbmtfcGxhdGZvcm1fb3duZXIiOiBmYWxzZSwgInNvdXJjZV9hc3NpZ25tZW50X2lkIjogImVhYjRhMjA5LWI2MjctNDQyMC1hNDMzLTM1NzE4ODAxNmYxZiIsICJyZXBvcnRzX3RvX3NvdXJjZV9wZXJzb25faWQiOiAiOTAxNjFkNTYtNGU3Ny00ODQ5LWExZGUtZDNkNzQxNmNjMDM3In0sIHsiY3NnIjogIlRNQVY3NDczIiwgImVtYWlsIjogInRtYXZlbkBpdGdjb21tLmNvbSIsICJwaG9uZSI6ICI2MDk0MTIwMDE4IiwgInRlY2hfaWQiOiAiNzQwOSIsICJlbmRfZGF0ZSI6IG51bGwsICJpc19maWVsZCI6IHRydWUsICJudF9sb2dpbiI6ICJicC10bWF2ZW4zNjYiLCAiZnVsbF9uYW1lIjogIlRyb3kgRWx0b24gTWF2ZW4iLCAicm9sZV90eXBlIjogIlRFQ0giLCAic3RhcnRfZGF0ZSI6ICIyMDI1LTEyLTIyIiwgImZ1c2VfZW1wX2lkIjogIjcwMDA4NSIsICJvZmZpY2VfbmFtZSI6ICJFZ2cgSGFyYm9yIiwgImlzX2xlYWRlcnNoaXAiOiBmYWxzZSwgImxvY2F0aW9uX2NvZGUiOiAiNDI3IiwgInBvc2l0aW9uX3RpdGxlIjogIlRlY2huaWNpYW4iLCAicmVwb3J0c190b19uYW1lIjogIkxhd3JlbmNlIEogU2NvdHQgSnIuIiwgInNvdXJjZV9wZXJzb25faWQiOiAiM2NkYmNlOWYtMWY4Yy00MzMzLWI4MGItYTNmYzkyNDQxOWFiIiwgImxpbmtfcGxhdGZvcm1fb3duZXIiOiBmYWxzZSwgInNvdXJjZV9hc3NpZ25tZW50X2lkIjogIjMyY2M0MTA1LTIyOWQtNDY4OS1iZDAwLWU0NGQzMTM3ZjI2ZiIsICJyZXBvcnRzX3RvX3NvdXJjZV9wZXJzb25faWQiOiAiOTdlNWU4YzgtMDZjNi00MzEzLWI2ZTEtZDQ0NjIzYzAwMTljIn1d', 'base64'), 'utf8')::jsonb
) as source_row (
  source_person_id uuid,
  source_assignment_id uuid,
  full_name text,
  email text,
  phone text,
  tech_id text,
  fuse_emp_id text,
  nt_login text,
  csg text,
  location_code text,
  position_title text,
  role_type text,
  is_field boolean,
  is_leadership boolean,
  start_date date,
  end_date date,
  office_name text,
  reports_to_source_person_id uuid,
  reports_to_name text,
  link_platform_owner boolean
);

do $$
declare
  v_company_id uuid;
  v_location_count integer;
begin
  select company.id
  into v_company_id
  from core.companies company
  where company.company_slug = 'integrated-tech-group'
    and company.company_status = 'active';

  if v_company_id is null then
    raise exception 'Integrated Tech Group company foundation is missing.';
  end if;

  if (select count(*) from itf_itg_roster_source) <> 38 then
    raise exception 'Expected 38 controlled ITG roster rows.';
  end if;

  if exists (
    select 1
    from itf_itg_roster_source source
    where source.location_code is not null
      and source.location_code not in ('410', '427')
  ) then
    raise exception 'ITG roster source contains an unauthorized location.';
  end if;

  select count(*)
  into v_location_count
  from core.company_location location
  where location.company_id = v_company_id
    and location.location_code in ('410', '427')
    and location.location_status = 'active';

  if v_location_count <> 2 then
    raise exception 'ITG locations 410 and 427 must both be active.';
  end if;

  if not exists (
    select 1
    from core.profiles profile
    where profile.is_platform_owner
  ) then
    raise exception 'A platform owner profile is required to record import provenance.';
  end if;
end;
$$;

update itf_itg_roster_source source
set target_roster_id = coalesce(
  (
    select provenance.roster_id
    from core.company_roster_entry_provenance provenance
    where provenance.source_system = 'itg-insight'
      and provenance.source_record_id = source.source_person_id::text
  ),
  gen_random_uuid()
);

insert into core.company_roster (
  id,
  company_id,
  profile_id,
  full_name,
  email,
  phone,
  worker_type,
  job_title,
  employment_status,
  company_location_id,
  hire_date,
  separation_date,
  invite_status,
  compliance_summary,
  notes,
  roster_record_kind
)
select
  source.target_roster_id,
  company.id,
  case
    when source.link_platform_owner then (
      select profile.id
      from core.profiles profile
      where profile.is_platform_owner
      order by profile.created_at
      limit 1
    )
    else null
  end,
  btrim(source.full_name),
  nullif(lower(btrim(coalesce(source.email, ''))), ''),
  nullif(btrim(coalesce(source.phone, '')), ''),
  nullif(btrim(coalesce(source.role_type, '')), ''),
  nullif(btrim(coalesce(source.position_title, '')), ''),
  'Active',
  location.id,
  source.start_date,
  null,
  case when source.link_platform_owner then 'Linked' else 'Not Invited' end,
  'Missing',
  null,
  'INTERNAL'
from itf_itg_roster_source source
cross join lateral (
  select company.id
  from core.companies company
  where company.company_slug = 'integrated-tech-group'
    and company.company_status = 'active'
) company
left join core.company_location location
  on location.company_id = company.id
 and location.location_code = source.location_code
 and location.location_status = 'active'
on conflict (id) do update
set
  profile_id = excluded.profile_id,
  full_name = excluded.full_name,
  email = excluded.email,
  phone = excluded.phone,
  worker_type = excluded.worker_type,
  job_title = excluded.job_title,
  employment_status = excluded.employment_status,
  company_location_id = excluded.company_location_id,
  hire_date = excluded.hire_date,
  separation_date = excluded.separation_date,
  invite_status = excluded.invite_status,
  roster_record_kind = excluded.roster_record_kind;

insert into core.company_roster_entry_provenance (
  roster_id,
  roster_owner_company_id,
  entry_authority,
  entry_channel,
  entered_by_company_id,
  entered_by_profile_id,
  source_system,
  source_record_id
)
select
  source.target_roster_id,
  company.id,
  'owner_company',
  'donor_migration',
  company.id,
  actor.id,
  'itg-insight',
  source.source_person_id::text
from itf_itg_roster_source source
cross join lateral (
  select company.id
  from core.companies company
  where company.company_slug = 'integrated-tech-group'
) company
cross join lateral (
  select profile.id
  from core.profiles profile
  where profile.is_platform_owner
  order by profile.created_at
  limit 1
) actor
on conflict (roster_id) do nothing;

insert into core.company_roster_identifier (
  roster_id,
  identifier_type,
  identifier_value
)
select
  source.target_roster_id,
  identifier.identifier_type,
  identifier.identifier_value
from itf_itg_roster_source source
cross join lateral (
  values
    ('tech_id'::text, case when source.link_platform_owner then null else nullif(btrim(coalesce(source.tech_id, '')), '') end),
    ('fuse_emp_id'::text, nullif(btrim(coalesce(source.fuse_emp_id, '')), '')),
    ('nt_login'::text, nullif(btrim(coalesce(source.nt_login, '')), '')),
    ('csg'::text, nullif(btrim(coalesce(source.csg, '')), '')),
    ('legacy_person_id'::text, source.source_person_id::text),
    ('legacy_assignment_id'::text, source.source_assignment_id::text)
) identifier(identifier_type, identifier_value)
where identifier.identifier_value is not null
on conflict (roster_id, identifier_type) do update
set identifier_value = excluded.identifier_value;

update core.company_roster child
set reports_to_roster_id = parent.target_roster_id
from itf_itg_roster_source source
join itf_itg_roster_source parent
  on parent.source_person_id = source.reports_to_source_person_id
where child.id = source.target_roster_id
  and child.reports_to_roster_id is distinct from parent.target_roster_id;

insert into core.company_roster_event (
  company_id,
  roster_id,
  event_category,
  event_type,
  event_detail,
  event_metadata,
  occurred_at,
  created_by_profile_id
)
select
  company.id,
  source.target_roster_id,
  'system',
  'donor_roster_imported',
  'ITG roster record imported from the donor application.',
  jsonb_strip_nulls(jsonb_build_object(
    'source_system', 'itg-insight',
    'source_person_id', source.source_person_id,
    'source_assignment_id', source.source_assignment_id,
    'location_code', source.location_code,
    'office_name', source.office_name,
    'position_title', source.position_title,
    'role_type', source.role_type,
    'is_field', source.is_field,
    'is_leadership', source.is_leadership,
    'reports_to_source_person_id', source.reports_to_source_person_id,
    'reports_to_name', source.reports_to_name
  )),
  now(),
  actor.id
from itf_itg_roster_source source
cross join lateral (
  select company.id
  from core.companies company
  where company.company_slug = 'integrated-tech-group'
) company
cross join lateral (
  select profile.id
  from core.profiles profile
  where profile.is_platform_owner
  order by profile.created_at
  limit 1
) actor
where not exists (
  select 1
  from core.company_roster_event event
  where event.roster_id = source.target_roster_id
    and event.event_type = 'donor_roster_imported'
);

create or replace view public.itf_company_roster_v
with (security_invoker = true)
as
select
  roster.id as roster_member_id,
  roster.company_id,
  company.company_name,
  company.company_slug,
  roster.profile_id,
  roster.full_name,
  roster.email,
  roster.phone,
  roster.worker_type,
  roster.job_title,
  roster.employment_status,
  roster.company_location_id,
  location.location_code,
  location.location_name,
  roster.reports_to_roster_id,
  supervisor.full_name as reports_to_name,
  identifiers.tech_id,
  identifiers.fuse_emp_id,
  identifiers.nt_login,
  identifiers.csg,
  identifiers.legacy_person_id,
  identifiers.legacy_assignment_id,
  import_event.event_metadata ->> 'office_name' as donor_office_name,
  provenance.entry_channel,
  provenance.source_system,
  provenance.source_record_id,
  case
    when provenance.entry_channel = 'donor_migration' then 'Donor import'
    when provenance.entered_by_company_id = roster.company_id then 'Company added'
    else 'Added on behalf'
  end as source_label
from core.company_roster roster
join core.companies company
  on company.id = roster.company_id
join core.company_product company_product
  on company_product.company_id = company.id
 and company_product.participation_status in ('active', 'review')
join ref.insight_products product
  on product.id = company_product.product_id
 and product.product_key = 'insight-telecom-fulfillment'
left join core.company_location location
  on location.id = roster.company_location_id
left join core.company_roster supervisor
  on supervisor.id = roster.reports_to_roster_id
left join core.company_roster_entry_provenance provenance
  on provenance.roster_id = roster.id
left join lateral (
  select
    max(identifier.identifier_value) filter (where identifier.identifier_type = 'tech_id') as tech_id,
    max(identifier.identifier_value) filter (where identifier.identifier_type = 'fuse_emp_id') as fuse_emp_id,
    max(identifier.identifier_value) filter (where identifier.identifier_type = 'nt_login') as nt_login,
    max(identifier.identifier_value) filter (where identifier.identifier_type = 'csg') as csg,
    max(identifier.identifier_value) filter (where identifier.identifier_type = 'legacy_person_id') as legacy_person_id,
    max(identifier.identifier_value) filter (where identifier.identifier_type = 'legacy_assignment_id') as legacy_assignment_id
  from core.company_roster_identifier identifier
  where identifier.roster_id = roster.id
) identifiers on true
left join lateral (
  select event.event_metadata
  from core.company_roster_event event
  where event.roster_id = roster.id
    and event.event_type = 'donor_roster_imported'
  order by event.occurred_at desc, event.created_at desc
  limit 1
) import_event on true;

comment on view public.itf_company_roster_v is
  'Company-authorized ITF roster projection composed from the platform roster, telecom identifiers, location, reporting line, and provenance.';

revoke all on table public.itf_company_roster_v from anon;
grant select on table public.itf_company_roster_v to authenticated;

do $$
declare
  v_company_id uuid;
  v_total integer;
  v_410 integer;
  v_427 integer;
  v_reporting_links integer;
begin
  select company.id
  into v_company_id
  from core.companies company
  where company.company_slug = 'integrated-tech-group';

  select count(*)
  into v_total
  from core.company_roster_entry_provenance provenance
  where provenance.roster_owner_company_id = v_company_id
    and provenance.source_system = 'itg-insight';

  select
    count(*) filter (where roster.location_code = '410'),
    count(*) filter (where roster.location_code = '427'),
    count(*) filter (where roster.reports_to_roster_id is not null)
  into v_410, v_427, v_reporting_links
  from public.itf_company_roster_v roster
  where roster.company_id = v_company_id;

  if v_total <> 38 or v_410 <> 12 or v_427 <> 25 then
    raise exception 'ITG roster import parity failed: total %, 410 %, 427 %.',
      v_total, v_410, v_427;
  end if;

  if v_reporting_links <> 35 then
    raise exception 'ITG reporting hierarchy parity failed: expected 35 links, found %.',
      v_reporting_links;
  end if;
end;
$$;
