-- Expand the starter library using recurring, generalized patterns from the
-- supplied historical CAN samples. These are editable manager starting points,
-- not automatic findings or employment decisions.

alter table core.corrective_action_template
  add column if not exists selection_help text,
  add column if not exists default_warning_level text not null default 'COACHING',
  add column if not exists default_outcome_type text not null default 'NONE',
  add column if not exists evidence_sources jsonb not null default '[]'::jsonb;

alter table core.corrective_action_template
  add constraint corrective_action_template_warning_ck
    check (default_warning_level in ('COACHING','VERBAL','WRITTEN','FINAL')),
  add constraint corrective_action_template_outcome_ck
    check (default_outcome_type in ('NONE','SUSPENSION','TERMINATION','RESIGNATION','JOB_ABANDONMENT'));

insert into core.corrective_action_template(
  template_key,category_label,event_family,title,selection_help,facts_prompt,
  expectation_statement,action_statement,context_schema,evidence_sources,
  default_warning_level,default_outcome_type
) values
  ('attendance_unexcused_absence','Attendance','ATTENDANCE','Unexcused absence or late call-out','Use when a scheduled employee did not report and notice or supporting context did not meet the company attendance procedure.','On {{incident_date}}, {{employee_name}} did not report for the scheduled assignment and did not provide notice consistent with the attendance procedure adopted by {{company_name}}.','{{employee_name}} is expected to report as scheduled and notify leadership through the adopted call-out process as soon as an absence or delay is known.','Leadership reviewed the attendance and call-out expectations, the operational impact, and the immediate improvement required.','["occurrence_dates","schedule","dispatch_events"]','["SCHEDULE","DISPATCH_EVENT"]','VERBAL','NONE'),
  ('attendance_ncns','Attendance','ATTENDANCE','No call, no show','Use when the employee neither reported for a scheduled assignment nor communicated with leadership.','On {{incident_date}}, {{employee_name}} was scheduled to work but did not report and did not communicate the absence to leadership.','{{employee_name}} is expected to report for every scheduled assignment or promptly contact leadership through the adopted call-out process.','Leadership reviewed the no-call/no-show concern and the sustained communication and attendance required going forward.','["occurrence_dates","schedule","dispatch_events"]','["SCHEDULE","DISPATCH_EVENT","COMMUNICATION_LOG"]','WRITTEN','NONE'),
  ('attendance_pattern','Attendance','ATTENDANCE','Repeated tardiness or absence pattern','Use when multiple documented dates show a recurring attendance pattern after prior coaching.','The documented dates show a recurring pattern in which {{employee_name}} did not report at the required time or was absent from scheduled work.','Regular, timely attendance and prompt communication are required for {{company_name}} to staff and manage daily operations.','Leadership reviewed the prior coaching, the documented dates, and the immediate sustained improvement required.','["occurrence_dates","schedule","prior_can_history"]','["SCHEDULE","DISPATCH_EVENT","CAN_HISTORY"]','FINAL','NONE'),
  ('performance_incomplete_route','Performance','PERFORMANCE','Incomplete route and service failure','Use when the route was not completed, packages were returned or unattempted, or required exception coding was incomplete.','On {{incident_date}}, {{employee_name}} did not complete the assigned route. The DSW and route evidence identify the resulting undelivered, unattempted, or uncoded service work.','{{employee_name}} is expected to complete the assigned route, apply accurate service codes, and immediately communicate any condition that may prevent completion.','Leadership reviewed route-completion, exception-coding, and escalation expectations and documented the measurable improvement required.','["route","dsw","stops","communication"]','["DSW","DISPATCH_EVENT","ROUTE_HISTORY"]','WRITTEN','NONE'),
  ('performance_no_communication','Performance','PERFORMANCE','Operational issue without management communication','Use when service deteriorated or assigned work could not be completed and leadership was not notified.','On {{incident_date}}, an operational or service issue developed on the assigned route and {{employee_name}} did not notify leadership in time for the company to respond.','{{employee_name}} is expected to communicate route, vehicle, safety, and service risks immediately when they may affect completion or customer service.','Leadership reviewed the required escalation path and the communication standard that must be followed on every assignment.','["route","dispatch_events","communication"]','["DSW","DISPATCH_EVENT","COMMUNICATION_LOG"]','WRITTEN','NONE'),
  ('service_code_85','Code 85','SERVICE','Code 85 packages','Use when the DSW route record reports one or more Code 85 packages.','The DSW record for {{incident_date}} reports Code 85 packages on the route assigned to {{employee_name}}. The route and count are attached to this notice as warehouse evidence.','Every package tendered for the route must be accounted for through delivery or the accurate scan, manifestation, service code, and service-cross process required by the adopted operating procedure.','Leadership reviewed the Code 85 evidence and the package-accountability steps required on every route.','["route","dsw","code_85_count"]','["DSW"]','WRITTEN','NONE'),
  ('service_code_27','Policy Violation','SERVICE','Code 27 without communication','Use when packages were coded 27 without the required leadership communication or supporting route context.','On {{incident_date}}, packages assigned to {{employee_name}} were recorded with Code 27 and the required communication or supporting context was not documented.','{{employee_name}} is expected to apply service codes accurately and notify leadership before unresolved service work is returned or coded when the procedure requires escalation.','Leadership reviewed the coding and communication procedure and the correction required on future routes.','["route","dsw","stops","communication"]','["DSW","PACKAGE_STATUS","COMMUNICATION_LOG"]','WRITTEN','NONE'),
  ('service_code_34_integrity','Policy Violation','SERVICE','Code 34 scanner integrity','Use when Code 34 was applied to residential or otherwise ineligible stops.','The service evidence for {{incident_date}} shows Code 34 applied to stops that did not meet the adopted eligibility requirements.','{{employee_name}} is expected to use only the service code supported by the actual stop conditions and preserve accurate scanner records.','Leadership reviewed scanner integrity, eligible code use, and the immediate correction required.','["route","package_status","stops"]','["DSW","PACKAGE_STATUS"]','WRITTEN','NONE'),
  ('pickup_window','Pick Up Failure','SERVICE','Pickup outside the service window','Use for a missed, early-closed, late, or otherwise noncompliant pickup window.','On {{incident_date}}, the assigned pickup was not completed onsite within the required service window.','All assigned pickups must be completed at the customer location within the documented window, including onsite package scanning and timely escalation of any impediment.','Leadership reviewed the pickup-window evidence and the timing, scanning, and communication requirements for future pickups.','["route","pickup_records","occurrence_dates"]','["DSW","PICKUP_RECORD","DISPATCH_EVENT"]','WRITTEN','NONE'),
  ('delivery_package_placement','Performance','SERVICE','Package placement or mailbox delivery','Use for front-door, mailbox, insecure-location, or customer-instruction placement failures.','The service and customer-feedback evidence for {{incident_date}} identifies package placement that did not follow the delivery instructions or adopted release-location standard.','{{employee_name}} is expected to confirm the correct address and place each package at the instructed or approved secure location. Mailbox delivery is not permitted.','Leadership reviewed the affected delivery evidence and the placement standard required at every stop.','["route","stops","customer_feedback","ppod"]','["DSW","CUSTOMER_FEEDBACK","PPOD"]','WRITTEN','NONE'),
  ('delivery_wrong_address','Performance','SERVICE','Delivery to the wrong address','Use when customer feedback, PPOD, or package evidence shows delivery at an incorrect address.','The evidence reviewed for {{incident_date}} indicates that one or more packages assigned to {{employee_name}} were delivered to an incorrect address.','Before releasing a package, {{employee_name}} is expected to verify the physical address, scanner information, and available delivery instructions.','Leadership reviewed the delivery evidence and the address-verification process required at every stop.','["route","stops","customer_feedback","ppod"]','["CUSTOMER_FEEDBACK","PPOD","PACKAGE_STATUS"]','WRITTEN','NONE'),
  ('delivery_signature_compliance','Misconduct','SERVICE','Required signature compliance','Use when a required recipient signature was missing, bypassed, or entered by the driver.','The delivery evidence for {{incident_date}} identifies a required-signature stop that was not completed in accordance with the signature procedure.','A required recipient signature must be obtained from the authorized recipient. {{employee_name}} must never sign on behalf of a customer or bypass the signature requirement.','Leadership reviewed signature compliance and the evidence-preservation steps required for every signature-controlled delivery.','["route","stops","signature_evidence"]','["DSW","PACKAGE_STATUS","SIGNATURE_RECORD"]','FINAL','NONE'),
  ('delivery_ppod_quality','Picture Proof of Delivery','SERVICE','Picture proof-of-delivery quality','Use when qualifying delivery photographs fail placement, clarity, privacy, or context requirements.','The PPOD evidence for {{incident_date}} includes one or more photographs that did not meet the adopted delivery-photo standard.','A compliant photo must clearly show the package at the secure release location and enough surrounding context to identify placement, while excluding people, addresses, labels, and other personal information.','Leadership reviewed the affected photographs and demonstrated the required PPOD framing, quality, and privacy standard.','["route","stops","ppod"]','["PPOD","CUSTOMER_FEEDBACK"]','COACHING','NONE'),
  ('conduct_refused_assist','Insubordination','CONDUCT','Failure to complete an accepted assist','Use when an employee accepted a direction to assist another route and did not complete or communicate the assignment.','On {{incident_date}}, {{employee_name}} accepted a leadership direction to assist another route but did not complete the assist or promptly communicate that it could not be completed.','{{employee_name}} is expected to follow safe and reasonable work direction and immediately raise any operational or safety concern that prevents completion.','Leadership reviewed the assignment, communication expectations, and the conduct required for future assist requests.','["dispatch_events","routes","communication"]','["DISPATCH_EVENT","DRIVER_ASSIST","COMMUNICATION_LOG"]','VERBAL','NONE'),
  ('safety_unreported_incident','Vehicle Incident','SAFETY','Vehicle incident not immediately reported','Use when a vehicle or property event was not reported to leadership immediately. Fault must be documented separately.','The evidence reviewed identifies a vehicle or property incident on {{incident_date}} involving {{employee_name}} that was not immediately reported through the company incident procedure.','After any contact or suspected incident, {{employee_name}} is expected to stop safely, protect the scene, preserve evidence, and notify leadership immediately.','Leadership reviewed the reporting timeline and incident procedure. Any fault or employment decision remains a separately documented manager determination.','["incident_subtype","route","vehicle","evidence","reporting_timeline"]','["INCIDENT_REPORT","VEDR","CUSTOMER_EVIDENCE","FLEET_RECORD"]','FINAL','NONE'),
  ('safety_fixed_object','Vehicle Incident','SAFETY','Fixed-object vehicle incident','Use for contact with a mailbox, fence, awning, structure, or other fixed object.','On {{incident_date}}, the vehicle operated by {{employee_name}} made contact with a fixed object. The location, route, reporting timeline, and available evidence are attached to this record.','{{employee_name}} is expected to maintain clearance, avoid unnecessary backing, use a safe exit plan, and stop and report any contact immediately.','Leadership reviewed the incident evidence, safe-maneuvering expectations, and any required retraining or follow-up.','["incident_subtype","route","vehicle","evidence"]','["INCIDENT_REPORT","VEDR","CUSTOMER_EVIDENCE","FLEET_RECORD"]','WRITTEN','NONE'),
  ('safety_moving_object','Vehicle Incident','SAFETY','Moving or parked vehicle incident','Use for contact with another vehicle, whether parked or moving. Fault must not be assumed without evidence.','On {{incident_date}}, the vehicle operated by {{employee_name}} was involved in contact with another vehicle. The route, reporting timeline, and available evidence are attached to this record.','{{employee_name}} is expected to use defensive-driving practices, minimize backing and driveway turnarounds, protect the scene, and immediately follow the incident-reporting procedure.','Leadership reviewed the available evidence and documented required coaching, retraining, or other manager-directed follow-up without making an unsupported fault determination.','["incident_subtype","route","vehicle","evidence"]','["INCIDENT_REPORT","VEDR","CUSTOMER_EVIDENCE","FLEET_RECORD"]','FINAL','NONE'),
  ('safety_distracted_driving','Policy Violation','SAFETY','Distracted driving or handheld phone use','Use when VEDR, observation, or incident evidence shows distraction, handheld phone use, or loss of proper vehicle control.','The safety evidence for {{incident_date}} identifies distracted driving or operation without maintaining proper attention and control.','{{employee_name}} is expected to maintain full attention, keep both hands available for safe control, and follow the adopted mobile-device and distracted-driving policy.','Leadership reviewed the evidence and the immediate safe-driving correction required.','["route","vehicle","vedr","evidence"]','["VEDR","INCIDENT_REPORT","LEADERSHIP_OBSERVATION"]','WRITTEN','NONE'),
  ('safety_speed_seatbelt','Policy Violation','SAFETY','Speeding or seatbelt noncompliance','Use when telematics, VEDR, or observation documents speeding or failure to use the seatbelt.','The safety evidence for {{incident_date}} identifies speeding or operation without proper seatbelt use by {{employee_name}}.','{{employee_name}} is expected to obey posted and condition-appropriate speeds and wear the seatbelt whenever the vehicle is in operation.','Leadership reviewed the evidence and the immediate, sustained safe-driving correction required.','["route","vehicle","telematics","vedr"]','["VEDR","TELEMATICS","LEADERSHIP_OBSERVATION"]','WRITTEN','NONE'),
  ('safety_vedr_interference','Policy Violation','SAFETY','VEDR disconnected or obstructed','Use when inspection or system evidence shows the installed safety camera was disconnected, obstructed, or disabled.','On {{incident_date}}, the installed VEDR safety system associated with {{employee_name}} or the assigned vehicle was found disconnected, obstructed, or otherwise not operating as required.','The VEDR system must remain connected, unobstructed, and operational. Any equipment problem must be reported immediately rather than altered or ignored.','Leadership reviewed the safety-system requirement and the immediate compliance expected on every vehicle assignment.','["vehicle","inspection","vedr"]','["VEDR","FLEET_INSPECTION"]','WRITTEN','NONE'),
  ('conduct_prohibited_weapon','Policy Violation','CONDUCT','Prohibited weapon','Use only when reliable evidence supports a violation of the company workplace-weapons policy.','Reliable evidence reviewed by leadership indicates that {{employee_name}} possessed a weapon in a location or circumstance prohibited by the policy adopted by {{company_name}}.','{{employee_name}} is expected to follow the adopted workplace-weapons policy at all company, customer, station, and vehicle locations.','Leadership reviewed the applicable policy, the evidence, and the manager-determined response.','["policy_reference","evidence","witnesses"]','["INCIDENT_REPORT","WITNESS_STATEMENT","POLICY_RECORD"]','FINAL','NONE')
on conflict do nothing;

create or replace function public.upsert_company_corrective_action_template(p_company_slug text, p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=core,public
as $$
declare v_company_id uuid; v_profile_id uuid:=core.current_profile_id(); v_key text:=p_payload->>'template_key'; v_version integer; v_id uuid;
begin
  select id into v_company_id from core.companies where company_slug=p_company_slug;
  if v_company_id is null then raise exception 'Company not found.'; end if;
  if not (core.is_platform_owner() or core.can_admin_company(v_company_id)) then raise exception 'Company admin access required.'; end if;
  if nullif(btrim(v_key),'') is null then raise exception 'Template key is required.'; end if;
  update core.corrective_action_template set is_active=false,updated_at=now() where company_id=v_company_id and template_key=v_key and is_active;
  select coalesce(max(version),0)+1 into v_version from core.corrective_action_template where company_id=v_company_id and template_key=v_key;
  insert into core.corrective_action_template(
    company_id,template_key,category_label,event_family,title,selection_help,facts_prompt,
    expectation_statement,action_statement,policy_reference,context_schema,version,
    created_by_profile_id,default_warning_level,default_outcome_type,evidence_sources
  ) values(
    v_company_id,v_key,p_payload->>'category_label',coalesce(nullif(p_payload->>'event_family',''),'GENERAL'),
    p_payload->>'title',nullif(p_payload->>'selection_help',''),p_payload->>'facts_prompt',
    p_payload->>'expectation_statement',p_payload->>'action_statement',nullif(p_payload->>'policy_reference',''),
    coalesce(p_payload->'context_schema','[]'),v_version,v_profile_id,
    coalesce(nullif(p_payload->>'default_warning_level',''),'COACHING'),
    coalesce(nullif(p_payload->>'default_outcome_type',''),'NONE'),coalesce(p_payload->'evidence_sources','[]')
  ) returning id into v_id;
  return jsonb_build_object('ok',true,'id',v_id,'version',v_version);
end $$;
